### ISSUE TITLE
Not in Amazon App

### ISSUE THREAD

**Issue by scargill** [hardillb/node-red-contrib-alexa-home-skill#1]
Lovely - very excited about the possibilities - but - it is no-where to be seen in the Amazon App - at least - not in the UK version. I went to all skills in the APP and searched for Node-Red - I even searched for just "Node" - nothing.

Can you please fix this so I can give this a go and write a review at http://tech.scargill.net

**Comment by hardillb** [comment]
It's with Amazon being reviewed, there will be an announcement when it's available

**Comment by hardillb** [comment]
The skill is now live for everybody Peter
