### ISSUE TITLE
Devices not in drop down list

### ISSUE THREAD

**Issue by andyuk5** [hardillb/node-red-contrib-alexa-home-skill#10]
Hi
As of my last message I have my account linked to my Alexa, and Alexa has now found my device list which I setup on your site. But I still do not see my device List on the node red drop down. Am I missing something. Sorry for being a pain and taking up your time.

Dragged node on to canvus clicked pencel entered my user name and password as I use to log in to your site.
Click Refresh
Clicked grip down with no sign of my device.
I have deleted my devices and started again by adding only one.
Alexa app see my new device but not node red drop down.
Regards,

Andy

**Comment by hardillb** [comment]
- What browser are you using
- What version of the node do you have installed (v0.1.15 is the latest)
- Is there anything in the browser console log (either when you submit the username and password or when you press the refresh button)

**Comment by hardillb** [comment]
Closing this as no contact from the raiser
