### ISSUE TITLE
New device not recognised by Alexa

### ISSUE THREAD

**Issue by cymplecy** [hardillb/node-red-contrib-alexa-home-skill#100]
Just added a new device (1st one in a long time) called Reading Light
Shows up fine but Alexa says "Sorry, I didn't find a device named reading light"

All other devices working fine.

Any ideas?

![image](https://user-images.githubusercontent.com/2357428/103220015-19bfae80-4917-11eb-81b1-2564f22916d1.png)

![image](https://user-images.githubusercontent.com/2357428/103220207-9a7eaa80-4917-11eb-8187-f1f35351041c.png)

**Comment by hardillb** [comment]
Did you remember to ask "Alexa, Discover devices"?

**Comment by cymplecy** [comment]
#LOL
 I did say it'd been a long time since I added one :-)
