### ISSUE TITLE
Device discovery not working

### ISSUE THREAD

**Issue by sugarat333** [hardillb/node-red-contrib-alexa-home-skill#101]
Hi there. I am running Node Red in a docker container (on the host networking).  

I am having problems getting any devices to be listed in the configuration node.  I have populated my username/password into the config node, but the Devices drop down box is not populated.  When I deploy, the config node does say 'connected', but again, no devices are listed.  I can confirm that I have created a test device on the website, but it is not coming through to the config node in Node-Red.  Any help appreciated.

**Comment by hardillb** [comment]
Check your browser console. You can trigger the same request by hitting the refresh button (next to the end of the drop down list)

Also is there a `@`, `%` or `&` in your password?

If so you will need to change it.

**Comment by hardillb** [comment]
Closing due to no response

**Comment by commputethis** [comment]
I know this is a really old issue, but... This is the issue I had with mine, but I had none of those 3 symbols in my password.  I could not get the devices to populate in Node-Red until I went and changed my password to contain no symbols.  After removing the symbols, the devices showed up.  Figured I would respond to let future people know this could be an issue for them.

**Comment by hardillb** [comment]
Further research - 

HTTP Basic Auth RFC 7617 says no control chars are allowed

https://datatracker.ietf.org/doc/html/rfc7617#page-5
