### ISSUE TITLE
[error] [alexa-home-conf:99cba767.0a7d98] Error: connect ECONNREFUSED xxx.xxx.xxx.xxx:8883

### ISSUE THREAD

**Issue by Ralanacam** [hardillb/node-red-contrib-alexa-home-skill#102]
Hello @hardillb! 
I am using its connection node with Alexa but for a while when I load the nodeRED flows it remains several minutes connecting and disconnecting in port 8883.
Could you check if I have something wrong?
username: Cameron.
Thanks in advance!

**Comment by Ralanacam** [comment]
Thank you very much for your quick reply!

Yes, it is true, when I implement all the flow is disconnected, but it remains between 1 and 5 minutes constantly disconnecting / reconnecting until it connects.
My question is, is it normal that it takes so long? I only have one instance of config shared on several nodes of the device.

**Comment by hardillb** [comment]
No that is not normal

It should try and fail to connect to port 8883 (I've just pushed an update to remove this) then try and succeed to connect on port 1883.

As I mentioned it will do this every time you deploy unless you change the deployment type.

Please apply the node update and try again

**Comment by Ralanacam** [comment]
**This is the last version installed in NodeRED:**
![image](https://user-images.githubusercontent.com/72660996/103773762-db6b7300-502b-11eb-851f-d0a4e33177f4.png)

**My account settings, on all nodes:**
![image](https://user-images.githubusercontent.com/72660996/103774271-972ca280-502c-11eb-9041-b42ea241c7d3.png)

**Configuration nodes, 7 nodes, same configuration:**
![image](https://user-images.githubusercontent.com/72660996/103774682-42d5f280-502d-11eb-9b28-4d0e8a580704.png)

**This is my debug:**
![image](https://user-images.githubusercontent.com/72660996/103773888-081f8a80-502c-11eb-9f71-3335b1a39bba.png)

And just now I deployed all nodes and the result is the same.
Connected after 3 minutes.

**Comment by hardillb** [comment]
The latest version is 0.1.19 pushed this morning I'd just not updated flows.nodered.org yet. It should be there now.

This is the first time you've mentioned the ECONNRESET error. That I'll have to look at tonight.

**Comment by hardillb** [comment]
OK, we'd run out of open file handles so I've added in 10 times more. Should be good now

**Comment by Ralanacam** [comment]
Works correctly!
Thank you!
