### ISSUE TITLE
Improvement request

### ISSUE THREAD

**Issue by bwims** [hardillb/node-red-contrib-alexa-home-skill#103]
Hello,

I've noticed that there are various climate sensors available for Alexa now, so I'm wondering if the routines you use/provide might be expandable to encompass humidity? Perhaps via the PercentageController as suggested [here](https://forums.developer.amazon.com/questions/202251/humidity-sensor-interface.html) .

Of course, that would not work for a barometer or rain gauge, but I wondered if you would consider it.

Thanks for all your hard work, either way!

**Comment by hardillb** [comment]
Support for any of the new device/sensor types would require a full ground up rewrite to support the new API level. I just don't have the time.

This skill is purely in maintenance mode
