### ISSUE TITLE
Is there a way to set rgb color?

### ISSUE THREAD

**Issue by Jastroger** [hardillb/node-red-contrib-alexa-home-skill#107]
Hi, 

is there a possibility to get rgb bulbs to change color using you home skill? I found "set color" but it does not show off the color wheel inside the alexa app. Maybe I misconfigured something?

Best,
Jan

**Comment by Jastroger** [comment]
Okay - brainfoo... 

Just had to use a color-convert node from HSV to rgb. Maybe this helps someone else, too.

**Comment by hardillb** [comment]
Yes, but the output from the skill will only be in Hue, Saturation and Brightness you will need to use something like [node-red-contrib-color-convert](https://flows.nodered.org/node/node-red-contrib-color-convert) to change it to RGB.

As to why it doesn't show up in the app I can't answer, try using the voice interface to trigger it.

E.g. Alexa set kitchen light, green
