### ISSUE TITLE
Not able to uninstall node-red-contrib-alexa-home-skill

### ISSUE THREAD

**Issue by brianblank** [hardillb/node-red-contrib-alexa-home-skill#108]
I am trying to uninstall the node-red-contrib-alexa-home-skill so that I can install another skill that has a naming conflict with this one.  However, the uninstall option is not presented to me.  I disabled the skill, and also deleted the credentials and removed all uses of the skill.  However, it only presents to me the option to disable the skill, but not to uninstall the skill.

Thanks in advance for any assistance.

![node-red-contrib-alexa-home-skill-nouninstall](https://user-images.githubusercontent.com/6259947/108944776-74c90580-7629-11eb-9dcd-559ded519144.png)

**Comment by hardillb** [comment]
That just means you didn't install it via the palette manger or by hand with npm  into the userDir.

You probably installed it globally, you will have to research how to remove globally installed nodes.

**Comment by 877dev** [comment]
Might be worth checking you have removed all nodes from your flows too.

**Comment by hex6ng** [comment]
@brianblank Were you able to remove your module?  I'm having the same issue and I don't see any way to remove it.

**Comment by brianblank** [comment]
> @brianblank Were you able to remove your module? I'm having the same issue and I don't see any way to remove it.
@hex6ng , I went on Discord to get advice from some Node Red experts.  They suggested to backup everything and re-install the software without the nodes that I want.  I haven't got around to that yet as that seems to be very time consuming and seems a bit excessive of a solution.  I just don't understand why I can't uninstall this feature while other node types have uninstall features.

**Comment by hardillb** [comment]
Being able to uninstall nodes has nothing to do with the node it's self.

You either still have a device node or config node on the system or you didn't install the node originally via the Palette Manager.

You can check by looking in your userDir (most likely `~/.node-red`) is the node listed in the `package.json` under dependencies or present in the `node_modules` directory? 

If you installed it from the command line with `npm install` and included the `-g` flag you will have to remove it on the command line the same way with `npm uninstall -g node-red....`

**Comment by brianblank** [comment]
Hi @hardillb  and thanks for providing some feedback.  I definitely would have installed this via the pallete.  My command line doesn't even have the NPM command available as the home assistant distribution provides a very minimal Linux command environment.
`node-red $ npm uninstall -g node-red-contrib-alexa-home-skill`
`-bash: npm: command not found`
My package.json file in /config/node-red directory does not reference this node nor can I find it in /config/node-red/node_modules directory.

**Comment by hardillb** [comment]
Without npm then pallet manager won't ever work because all it does is shell out that command.

The Home Assistant folks have done some crazy stuff, you will have to take it up with them, I offer no support at all for that setup unless you can reproduce it outside.

**Comment by compujunk** [comment]
I have the same problem with homeassistant. I can delete all pallets, but not this one.
in the .config.nodes.json it says the location "file": "/opt/node_modules/node-red-contrib-alexa-home-skill/alexa.js" only that path doesn't exist. All other pallets are neatly in /node-red/node_modules/.
at the home assistant community they refer me to the maker of the pallete in this case so here.
