### ISSUE TITLE
https://alexa-node-red.bm.hardill.me.uk/ is down?

### ISSUE THREAD

**Issue by SergioRius** [hardillb/node-red-contrib-alexa-home-skill#110]
I think https://alexa-node-red.bm.hardill.me.uk/ is down from yesterday evening. But could be my computer/network/fw blocking or something.
Trying to login the site always replies:
![image](https://user-images.githubusercontent.com/1693727/112747652-fa3c2e80-8fb6-11eb-9343-80c5d1170b81.png)

Tried with Chrome and Firefox.
Using my devices throws an error in Alexa saying the server did not respond.
Node-red also was showing some errors in the debug window this morning (I cleared them)

**Comment by hardillb** [comment]
Nope, all fine with up to date Letsencrypt certs

**Comment by SergioRius** [comment]
It seems something with pfsense+pfbl. As I can login using the phone. Could be that it has updated block lists and adding something that messes it.
I'll try to find the problem and post back.

**Comment by SergioRius** [comment]
Look, you're antisocial and malicious. Just like me:
`DNSBL-HTTPS,Mar 28 17:38:39,alexa-node-red.bm.hardill.me.uk,10.1.2.71,Unknown,TLD,DNSBL_Malicious,me.uk,AntiSocial_BD,-`

Note: That's the default block lists in pfBlockerNG. The whole .me.uk is wilcard blocked.

**Comment by hardillb** [comment]
Well that sounds stupid, I'll leave it up to you to tell pfSense to fix their broken shit

**Comment by SergioRius** [comment]
No thanks. It's a lost case to get anything from them. You know, they love to charge for listening.
I've disabled that list and as soon as I have some time, swap it for pihole. It was a nightmare to find the block log entries. And filters didn't work most of the time.
