### ISSUE TITLE
Reconnecting Issue

### ISSUE THREAD

**Issue by INDRANI125** [hardillb/node-red-contrib-alexa-home-skill#111]
Despite of giving my correct credential of my correct password of https://alexa-node-red.bm.hardill.me.uk/..today I am not able to see ,y registered devices it is showing only reconnecting. I am running it in only one nodered instance.Please help.

**Comment by hardillb** [comment]
If the nodes are constantly reconnecting then you MUST have either 2 instances or more than one config node.

You can check the config nodes by click on the menu in the top right hand corner and selecting "Configuration nodes". You should only have ONE `alexa-home-conf` instance that should be shared by all device nodes.

**Comment by hardillb** [comment]
If you still have a problem, comment here. Do NOT open another issue. You will have to supply a LOT more information before I'll be able to offer anything other than the response I already have.
