### ISSUE TITLE
If the nodes are constantly reconnecting then you MUST have either 2 instances or more than one config node.

### ISSUE THREAD

**Issue by INDRANI125** [hardillb/node-red-contrib-alexa-home-skill#112]
If the nodes are constantly reconnecting then you MUST have either 2 instances or more than one config node.

You can check the config nodes by click on the menu in the top right hand corner and selecting "Configuration nodes". You should only have ONE `alexa-home-conf` instance that should be shared by all device nodes.

_Originally posted by @hardillb in https://github.com/hardillb/node-red-contrib-alexa-home-skill/issues/111#issuecomment-826099002_

**Comment by hardillb** [comment]
I've closed this already
