### ISSUE TITLE
DEVICE DISCOVERY PROBLEM

### ISSUE THREAD

**Issue by stijojoseph** [hardillb/node-red-contrib-alexa-home-skill#113]
I have enabled node red in alexa app now,
on node red setting on my pi is also correct but still alexa is not recognising it in discovery devices
On my raspberry Pi 4B I installed nodered & install nodered Alexa contribute skill in that way everything is fine

username 
stijojoseph
location ; India
device name; light

**Comment by hardillb** [comment]
You have explicitly told Alexa to "Discover devices"?

**Comment by stijojoseph** [comment]
yes tried both methods  ie manually searching devices and also by voice also tried

**Comment by stijojoseph** [comment]
![Screenshot (405)](https://user-images.githubusercontent.com/52098974/118258890-0a0fc380-b4ce-11eb-9d4c-6df9ced31b12.png)
![WhatsApp Image 2021-05-14 at 4 03 00 PM](https://user-images.githubusercontent.com/52098974/118258915-1267fe80-b4ce-11eb-87c8-db9d6cc650db.jpeg)


Iam using the alexa mobile app

**Comment by hardillb** [comment]
You don't have any devices on the service. Also that node is not the one linked to the this service.

**Comment by hardillb** [comment]
node-red-contrib-alexa-local != node-red-contrib-alexa-home-skill

**Comment by stijojoseph** [comment]
i followed this one ,i think then this tutorial might be wrong ,Anyway thank you so much for redirecting me
https://www.thedigitalpictureframe.com/voice-control-digital-photo-frame-amazon-echo-mqtt-node-red/
