### ISSUE TITLE
Error: connect ECONNREFUSED 34.240.81.189:8883

### ISSUE THREAD

**Issue by acquistidiso** [hardillb/node-red-contrib-alexa-home-skill#114]
I've got the same issue like in the object. Could you help me? I'm grateful for the good job you made with bridge

**Comment by hardillb** [comment]
Ignore it and wait 30 seconds. The node will connect on port 1883

**Comment by acquistidiso** [comment]
I made it, but nothing happens. Sorry, but there is also the message: "Error: Connection refused: Not authorized". The reason could be I've changed my password on your platform?
 
![node_issues 14 05 2021](https://user-images.githubusercontent.com/84189420/118283754-fe250100-b4cf-11eb-9aa6-c2df2e560468.JPG)

**Comment by hardillb** [comment]
If you've changed the password you will also obviously need to update the password in the config node to match.

But that is totally different error to how you opened this issue.

**Comment by acquistidiso** [comment]
Sorry for my mistake. If you mean updating password on https://flows.nodered.org/node/node-red-contrib-alexa-home-skill I made it, I didn't know if could be useful, but I've also disconnected and riconnected skill connection in my alexa-account, but still doesn't work

**Comment by hardillb** [comment]
The username and password on https://alexa-node-red.bm.hardill.me.uk/ needs to match the username/password you entered into the config node in the editor (the Account entry in the device node)

**Comment by acquistidiso** [comment]
You have perfectly found the issue. I matched username/password also in config node and everything start again working. Thank you very much  for your kindness and professionalism
