### ISSUE TITLE
Update for new supported plattforms?

### ISSUE THREAD

**Issue by Senbei123** [hardillb/node-red-contrib-alexa-home-skill#115]
Hi,

first of all thanks for your work so far. Even when I think about, that this was done 5 years ago. In IOT time it is nearly 2-3 decades. ;)
Do you think it will be possbile to extend your service with the "new" plattforms? A somehow "full" list looks like this:

    Alarm Control Panel
        Arming
        Disarming
     Camera
    Climate
        Set Thermostat Temperature
        Thermostat Mode
    Cover
        Open/Close/Raise/Lower
        Set Cover Position
        Set Cover Tilt
        Garage Doors
    Fan
        Fan Speed
        Fan Preset Mode
        Fan Direction
        Fan Oscillation
    Light
        Brightness
        Color Temperature
        Color
    Lock
        Unlocking
    Media Player
        Change Channel
        Speaker Volume
        Equalizer Mode
        Inputs
        Playback State
        Seek
    Switch
    Timer
    Vacuum

**Comment by hardillb** [comment]
This is not possible without a full rewrite of the service to change the version of the Alexa Smart Home API. This skill is in maintenance mode, there will be no new device types added.
