### ISSUE TITLE
Can unlock smart locks with the app?

### ISSUE THREAD

**Issue by bwims** [hardillb/node-red-contrib-alexa-home-skill#116]
Hi, thanks very much for your work!

I have got lock state and locking working with my garage door.  I saw in your comment here https://github.com/hardillb/node-red-contrib-alexa-home-skill/issues/91#issuecomment-729222769  that you said "You can not unlock the device via voice as it is not secure".

I think since then Amazon have changed things so that you cannot unlock via the app unless you enable it, which seems bizarre.

[This article](https://www.array.care/hc/en-us/articles/360009232953-How-do-I-enable-my-Alexa-App-Alexa-Device-to-unlock-my-Array-Smart-Deadbolt-) has examples of the settings that presumably need to be coded into the server side.

I'm guessing this will be too much effort, but I thought I would ask in case I'm wrong!

Either way, many thanks again!

B.

**Comment by hardillb** [comment]
Unlocking will not be supported.
