### ISSUE TITLE
How to implement binary sensor

### ISSUE THREAD

**Issue by grochib** [hardillb/node-red-contrib-alexa-home-skill#117]
Hardware: raspberry pi 3b, Hassio-OS, deconz Conbee II

I'm a big fan of Home Assistant, Node Red and especially the possibility to use Alexa with my smart home devices. 
With this skill it was easy to toggle switches.

But I really don't understand how to query the state from my new Xiaomi window sensor. It is controlled by the deconz Conbee II and discovered in Home Assistant as a binary sensor, therefore also visible in node red. 
I know the logic of using switches with your skill: Alexa home node, switch node with command and a node with the home assistant device.

But I really do not understand what I am supposed to do in order to get an answer if my window sensor is open or not. 

Of course I checked the documentation but I really cannot grasp the logic of it.

So please let me ask you very politely for your step by step guidance on what to do, what nodes to use and what messages to select in order to make this work.

Thank you so much for your help and time!

**Comment by hardillb** [comment]
You don't.

Sensors states are not a supported device type or trait with this service.
