### ISSUE TITLE
Problem with SetTargetTemperatureRequest ?

### ISSUE THREAD

**Issue by bwims** [hardillb/node-red-contrib-alexa-home-skill#118]
I have been using this system for a Sonoff thermostat as described in "Not enough Tech" for a year or two and Alexa has suddenly started complaining when I ask for a temperature change.  Although the change is implemented, it says "I'm not quite sure what went wrong" instead of saying "Heating set to xx" as in the past.

Could it be the response format has altered?  Here is a sample of what I send.

```
{
  "topic":"Hall",
  "name":"Heating",
  "_messageId":"52bff8a9-7e50-46fd-bac2-4062038918f1",
  "_applianceId":"57292",
  "_confId":"92f20cb0.aff6",
  "command":"SetTargetTemperatureRequest",
  "extraInfo":{},
  "payload":true,
  "_msgid":"edddf5d9.14d098",
  "extra": {
    "targetTemperature":{
       "value":23
    }
  }
}
```

**Comment by hardillb** [comment]
Nothing has changed in the skill, so it has to be something on Amazon's side.

It is unlikely that this is intentional as the skill uses and old version of the API (and will not be updated) that should not be being changed by Amazon so my best suggestion is to just wait and see if it changes
