### ISSUE TITLE
Alexa sees the devices but does not respond in your node

### ISSUE THREAD

**Issue by swilson86** [hardillb/node-red-contrib-alexa-home-skill#12]
I followed all the steps to install your skill with Amazon Echo, updated node-red with your nodes, added your nodes to an existing working flow, and got stuck. The Alexa Home node does not output anything at all. I followed all the instructions on your page at https://alexa-node-red.bm.hardill.me.uk/docs

Knowns: Alexa recognizes the 3 new devices. I know internally my systems are working as they communicate with MQTT on my network. Node-Red flows that I am using are working perfectly. I chose 3 different devices... 1) A simple door that is detected either open/closed using the lock status 2) A percentage to open/close drapes  3) Garden moisture sensor just to receive value from Alexa. 

Is there a critical item in your documentation missing? Do I have to say something like “Alexa what is the status of the front door?” etc.  I suspect I have overlooked something simple, or it isn't documented.

**Comment by hardillb** [comment]
What commands are you trying to use to interact with your devices?
e.g. for the blinds assuming the device is called blinds it should be something like:

"Alexa, set the binds to 50%" 

Also what response do you get from Alexa when you ask the question. 

Can you attach a screen shot of your Node-RED flows so I can see how you've wired things together

**Comment by hardillb** [comment]
Also the moisture sensor isn't going to work at all as there is no way to query a percentage value

**Comment by swilson86** [comment]
Ah... I think you just gave me the critical missing clue... the NAME of the device is the word that Alexa detects? I will test that and get back to you.

**Comment by swilson86** [comment]
Thank you, thank you! That was the missing clue... the word or phrase that you name your device becomes that which Alexa acts upon. 

You have done an outstanding job with your software. I recommend a wee bit more documentation. It does seem strange to say "Alexa, open the blinds to 50%" instead of "Alexa, open the blinds half way." Alas, a limitation of Amazon.
