### ISSUE TITLE
Not able to uninstall node-red-contrib-alexa-home-skill

### ISSUE THREAD

**Issue by compujunk** [hardillb/node-red-contrib-alexa-home-skill#120]
I have the same problem as issues "Not able to uninstall node-red-contrib-alexa-home-skill #108"
also with home assistant. I can delete all pallets, but not this one.
in the .config.nodes.json it says the location "file": "/opt/node_modules/node-red-contrib-alexa-home-skill/alexa.js" only that path doesn't exist. All other pallets are neatly in /node-red/node_modules/.
at the home assistant community they refer me to the maker of the pallete in this case so here.

**Comment by hardillb** [comment]
Duplicate #108 

As I said before, this is a home assistant problem, I have no idea why it would be installed somewhere different to any other node.

The `.config.node.json` file is updated at Node-RED startup with the location of all the nodes it can find, so if the node is not where it's shown (remember that will be in the Node-RED container, not the host) then something is very wrong, but it has nothing to do with the node it's self.

Also as stated in the other issue, I don't offer any support for this under home assistant, it's not an an environment I use or have any interest in as they do too many strange things with their node-red setup
