### ISSUE TITLE
Error: Connection refused: Not authorized

### ISSUE THREAD

**Issue by clarcksp** [hardillb/node-red-contrib-alexa-home-skill#124]
Hi,
I'm using Home Assistant with Node-Red and followed the steps to configure your node.
Installation is apparently ok. When I link the account, the devices I created already appear.
However, in a few seconds I start to get an alert in the debug:

12/29/2021 06:53:46node: 125ae5c267cbcc09
msg: error
"Error: Connection refused: Not authorized"

And automation doesn't work.
I've done the reinstallation of node and the problem persists.

**Comment by hardillb** [comment]
- Is this a new account?
- What is your username?
- And are there any entries in the Node-RED logs (not the debug sidebar the actual console logs from Node-RED)
- Do you get the list of devices in the drop down in the alexa-in node?

**Comment by clarcksp** [comment]
- Yes the account is newly created.
- Nickname: ronaldosc86
- Precisely the message I reported is what appears in the Node-Red log bar in sequence, every few seconds.
- Yes, from the moment I log in with my account, I close the automation window, open it again and show all the devices created, but when I Deploy the information Reconnection/Disconecct appears under the created node and the connection error log starts intermittently.

**Comment by hardillb** [comment]
Please follow this link: https://alexa-node-red.bm.hardill.me.uk/lostPassword
It will ask for the email address you used to set up the account, then email you a link to a password change form.
You can enter the old password again but it will reset what is stored in the database and should let you login in.

**Comment by clarcksp** [comment]
I just noticed something strange, if I enter my login and new password, it brings me a panel with only two devices. But if I enter the old password it loads me a panel with the devices I had created.
The same login has two different passwords.

**Comment by hardillb** [comment]
That's not possible.

Please follow the instructions to change the password again I want to watch the logs

**Comment by clarcksp** [comment]
I've just done the procedure for a browser that I've never used, just to avoid cockies.
I changed the password to a generic password, entered the panel and it showed only two Devices (Exemplo, A1).
I logged out and then with the same login, I entered the password I used when I registered the first time, then the system brought me all the devices I had created (Exemplo, A1, A2 and A3)

**Comment by hardillb** [comment]
OK, there is something very wrong with your account that doesn't make any sense, It is missing a bunch of required fields.

I'm going to remove all traces from the database (including the devices) and you will need to create a new account 

You will need to unlink the skill in the Amazon app and then make sure you hit the log out button on the website and remove all the device nodes (and the config node) from your node-red instance before starting again.

**Comment by clarcksp** [comment]
I created a completely clean account with another login included.
Now it didn't show the error I mentioned. And node status is green/connected
