### ISSUE TITLE
Missing conf node

### ISSUE THREAD

**Issue by bkr1969** [hardillb/node-red-contrib-alexa-home-skill#126]
I know this is not maintained anymore, but why did my stuff just disappear from Node Red? I cannot run some of my flows because there is no longer an alexa-home-conf node. Can anyone help? (Or point me to how I can trigger Node Red flows with alexa now)

**Comment by hardillb** [comment]
There is no active development, not the same as being totally unmaintained, but anyway.

Node-RED nodes do not just magically disappear, you must have done something. You need to supply a LOT more information, there is not enough there to even speculate.

**Comment by bkr1969** [comment]
I'm not sure what else I can supply.  I loaded my flows this morning and got an error message saying "Flows stopped, missing node..." and all of my alexa-home-conf nodes were gone.  They are greyed out in my palette as well.

**Comment by jaymemaurice** [comment]
Everything seems to be working here for me. 
Are you trying to add a node?? Do you have node-red-contrib-alexa-home-skill in your node red pallet?
Can you log in to https://alexa-node-red.bm.hardill.me.uk/?
When you try to add a node, search for alexa
![image](https://user-images.githubusercontent.com/38895319/172636709-a420d6a0-cd21-41c0-a30a-4e69b3a51ae3.png)

**Comment by hardillb** [comment]
Still not enough information to work with, but you have at least supplied a hint (as in the actual error message rather than your attempt at interpreting it....)

Provide the Node-RED start up console log.

But best guess is that as some point you have installed another Alexa based node that has a name clash (assuming it is just the config node that is missing). Or you have changed something, e.g. NodeJS version, moved you userDir (which would lose all your 3rd party installed nodes)

**Comment by bkr1969** [comment]
> Everything seems to be working here for me. Are you trying to add a node?? Do you have node-red-contrib-alexa-home-skill in your node red pallet? Can you log in to https://alexa-node-red.bm.hardill.me.uk/? When you try to add a node, search for alexa ![image](https://user-images.githubusercontent.com/38895319/172636709-a420d6a0-cd21-41c0-a30a-4e69b3a51ae3.png)

![image](https://user-images.githubusercontent.com/42385989/172638748-6e5dfca8-add0-48e7-bbe1-f3502377a58d.png)

**Comment by bkr1969** [comment]
See how the -conf is greyed out?  I cannot use that node in my flow.  It is what was missing this morning.

**Comment by bkr1969** [comment]
My biggest problem is that all flows have been stopped (node red essentially isn't running) because the config node is missing and I can't delete from the palette because it's "in use."  can anyone at least help me get rid of the whole alexa node?

**Comment by hardillb** [comment]
Supply the logs like I asked for and we can probably fix it all.

**Comment by bkr1969** [comment]
Please tell me where to find the logs you'd like

**Comment by hardillb** [comment]
No idea, you've not supplied any information about how you are running Node-RED.

**Comment by bkr1969** [comment]
OK...here is what I know.  I'm sorry that I'm just an end user and not familiar with the inner workings.  I have HA running on HA  Blue (ODROID).  I  installed Node Red via HACS.  What else can I tell you that will be helpful?

**Comment by hardillb** [comment]
Then you'll need to go talk to HA folks about where they've hidden the Node-RED logs.

**Comment by bkr1969** [comment]
![image](https://user-images.githubusercontent.com/42385989/172666186-74c28391-95b0-4d70-8077-fc4865d4ada5.png)

**Comment by bkr1969** [comment]
![image](https://user-images.githubusercontent.com/42385989/172679190-2b1ebdb1-adf4-4dc8-92c4-14d03dfb4095.png)

**Comment by hardillb** [comment]
Those images don't tell me anything new, as I mentioned, I need the Node-RED console log from when it starts.

I don't use HA at all, so you will need to talk to the people that build the Node-RED HA plugin and get them to tell you where the log are.

**Comment by bkr1969** [comment]
Are you able to tell me how to remove this from my palette?

**Comment by frenck** [comment]
@bkr1969 This has been part of the release notes of the Home Assistant Node-RED add-on, which warns of this breaking change:

<https://github.com/hassio-addons/addon-node-red/releases/tag/v12.0.0>

This node is no longer built-in by default. You can, however, as per releas notes, install them manually. Add it to the add-on configuration in that case.

@hardillb Sorry for the noise, even though this was described as a breaking change (and released as a major version number) this has been missed by the issue author.

../Frenck
