### ISSUE TITLE
Nodes not working since last nodered update

### ISSUE THREAD

**Issue by Patrick762** [hardillb/node-red-contrib-alexa-home-skill#127]
![grafik](https://user-images.githubusercontent.com/80690443/172944133-09726e6b-93af-4305-bd3f-09f6aea39f2c.png)

The Nodes worked fine until a few days ago.

Node-Red Version 2.2.2
Running on Home Assistant OS 8.1

**Comment by hardillb** [comment]
https://github.com/hassio-addons/addon-node-red/releases/tag/v12.0.0
