### ISSUE TITLE
Flows stopped due to missing node types - alexa-home-conf

### ISSUE THREAD

**Issue by ElektroPrzewodnik** [hardillb/node-red-contrib-alexa-home-skill#129]
I'm not able to start node-red because of missing node type alexa-home-conf
However I'm not able also to remove or disable node-red-contrib-alexa-home-skill. How to move on?
![image](https://user-images.githubusercontent.com/22837585/178052370-2ea21cfa-9a43-4dc8-83a4-dfd3c81f1f7d.png)
Node-RED in Home Assistant

**Comment by hardillb** [comment]
You have to delete the config node before you try and remove it, you can list all config nodes from the hamburger menu in the top right hand corner
