### ISSUE TITLE
Payload for percentage-type commands are not numeric

### ISSUE THREAD

**Issue by maxwellhadley** [hardillb/node-red-contrib-alexa-home-skill#13]
There seems to be a discrepancy between your documentation (https://alexa-node-red.bm.hardill.me.uk/docs#buildFlows) and the message object currently being output by an alexa-home node for a SetPercentageRequest command. Your documents say the **payload** field should be the requested percentage as a number, but it is actually an object, having a **value** field which holds the number. The same applies for percentage increase & decrease commands – however the corresponding temperature commands do use a numeric **payload**.

Is this a documentation error, a bug, or just something Amazon have changed?

**Comment by hardillb** [comment]
Yes that probably should have been a straight value to be consistent, but I'm not changing it now as that may break existing users.

I'll update the doc next time I push an update.

**Comment by hardillb** [comment]
Actually I've changed my mind, as it's the only one that differes I'll fix the node but it will probably not get pushed until the end of the weekend

**Comment by maxwellhadley** [comment]
If it were starting with a clean sheet of paper, I'd make the payload an object, with **value**, **units** and **command** fields (where **command** would be _"set"_ or _"change"_ depending on the request type, and **units** would be _"%"_, or either _"degC"_ or _"degF"_ depending on the temperatureunits set for the active Alexa device). That way, most following nodes would only have to look at the message **payload** to work out what to do. But I suspect we are too far down the road to change now.

**Comment by hardillb** [comment]
Values are always in centigrade as per the Amazon docs

The full command is already there as msg.command

Nothing else is changing.

**Comment by hardillb** [comment]
This has now shipped (if it didn't a long time ago)
