### ISSUE TITLE
"Connected" "Disconnected" "Connected" ....

### ISSUE THREAD

**Issue by sbolten** [hardillb/node-red-contrib-alexa-home-skill#134]
Hi, just reinstalled from scratch (changed raspi hardware). Now all my home nodes show "connected" for a couple of seconds and then switch to "Disconnected" - after a while again "connected" and so on...
Only difference I see compared to my original installation is that I am now running node-red in a docker image with bridged network.

How can I debut what is going wrong? Any log files somewhere?

Regards,

STephan

**Comment by hardillb** [comment]
> Only difference I see compared to my original installation is that I am now running node-red

This implies the old version is still running, that will not work. You need to make sure you only ever have one instance trying to connect.

Even if you have removed the device nodes from the old instance you must also remove the config node.

Better yet just make sure the old Node-RED instance isn't running at all.

**Comment by sbolten** [comment]
Thx a lot for this super quick response. That was indeed the problem. 

Best regards,

Stephan
