### ISSUE TITLE
Add Blind device

### ISSUE THREAD

**Issue by DavidBurstein** [hardillb/node-red-contrib-alexa-home-skill#135]
Would it be possible to add a blind (cover) device type?
At present I'm having to use a switch device.

Saying "Alexa turn on the studio blinds"  seems weird.
"Alexa close the studio blinds" is better.

Simplest would be to open or close. Optionally pass the blind closure %

TIA

**Comment by hardillb** [comment]
Duplicate https://github.com/hardillb/node-red-alexa-home-skill-web/issues/118

**Comment by NorthernMan54** [comment]
A workaround I have been using for years is to create a routine triggered by phrasing you want to use.

ie Alexa, open bedroom blinds

then have the routine open your blinds
