### ISSUE TITLE
Alexa home response rounds SetTargetTemperatureRequest return values

### ISSUE THREAD

**Issue by niklas1375** [hardillb/node-red-contrib-alexa-home-skill#136]
Whenever I issue a "SetTargetTemperatureRequest" to my alexa home skill with a non-whole number such as "Set the living room to 21.5°C" it will correctly execute that request and answer that the heat has been set to (in this case) 22°C rounding the number I requested. It's not a dealbreaker or big issue but it does bug me. Are half degrees not a thing for Alexa? :D 

I couldn't find anything regarding this in the docs regarding the SetTargetTemperatureRequest so I'm hopeful the issue is either known or preventable.

**Comment by hardillb** [comment]
This is all been done on the Amazon side, nothing you can control

**Comment by niklas1375** [comment]
Thanks for the fast reply :)
