### ISSUE TITLE
Existing devices offline, new devices not discovered

### ISSUE THREAD

**Issue by r31337** [hardillb/node-red-contrib-alexa-home-skill#14]
Hi,

After working flawlessly for months something broke.

NodeRed connects and discovers the devices from the Bridge as normal. But the Alexa app reports that the devices are offline/not responding. The alexa app also cannot discover any new devices added to the Bridge.

I tried connecting via a different NodeRed instance, no change (connected but no messages). I tried disabling the skill, deleting all devices from Alexa App and re-linking, again no change.

What did work was creating a new Bridge account, re-creating my device list and re-linking in the Alexa app....

Thanks,
Ryan

**Comment by hardillb** [comment]
Can you supply your original account username so I can check some details in the db

**Comment by r31337** [comment]
Sure: -iddqd-

**Comment by hardillb** [comment]
Looks like the Amazon system is not requesting a new OAuth token when the old one expires (every 3 months).

Sounds like everybody who signed up when it went live is going to break real soon now.

There goes my weekend working out how to fix this then.

**Comment by r31337** [comment]
Sorry to be the bearer of bad news! I spotted another similar comment on your blog so figured as much.

**Comment by hardillb** [comment]
OK, I've pushed the expiry out on all the tokens to 2117 and it seams to work, If you can go back to the old id and test that would be useful
