### ISSUE TITLE
devices in node red are switching always from "connect" to "disconnected" and back again

### ISSUE THREAD

**Issue by scobby** [hardillb/node-red-contrib-alexa-home-skill#16]
in the node red frontend the alexa devices are constantly switching connection state. 
is this only on my side? or a common problem?

**Comment by hardillb** [comment]
That implies you have 2 instances trying to connect. You can only have 1 client connected at any given time.

If you have 2 as the second connects it disconnects the first which will then reconnect again kicking the other off.

**Comment by scobby** [comment]
oh, you are right, the second instance was running too, thougt i disabled it.
thx for the super fast help!

**Comment by scobby** [comment]
can be closed
