### ISSUE TITLE
Not really issue, looking to learn mqtt to alexa home response

### ISSUE THREAD

**Issue by MuddyVT** [hardillb/node-red-contrib-alexa-home-skill#17]
Hello, I have installed your skill and can see the devices.  My objective in adding your skill is primarily to get temperatures from house devices delivered by voice the echo. "Alexa what is the boiler temperature"
I already use node red to pull data from many esp8266 running espeasy firmware to MQTT to node red dashboard.  I also have raspberry pi with one wire temperature serial strings feeding MQTT.  
Just looking to learn how to connect mqtt data to the Alexa home  response.  
Is there a forum or source of examples I have missed?
Thank you

**Comment by hardillb** [comment]
Shot gunning the same message on multiple channel is not a great way to get people to help. As mentioned on the about page, the #alexa channel on the Node-RED slack channel is probably the best place, but you will have to be patient

**Comment by MuddyVT** [comment]
my apologies, trying on your site the page never finished so I 'assumed' it
did not upload.
I moved to the other site after I thought that failed.
Delete what is offensive, never my intention.
