### ISSUE TITLE
No devices in drop-down list

### ISSUE THREAD

**Issue by hanpude** [hardillb/node-red-contrib-alexa-home-skill#21]
Hi hardillb,

in the alexa home node I don't get any device listed. After clicking refresh, the browser java-script console gives me a 404 (GET http://10.100.100.10:1880/alexa-home/devices/f4e10ad1.9b3268 404 (Not Found)). I am using the latest version of node-red and node-red-contrib-alexa-home-skill. node-red is connected to your mqtt server (gui indicator and netstat established), devices are shown on your web server and discovered by Alexa.
I already tried a lot of things (restart node-red, uninstall node-red-alexa-home-skill, checked out an old version of node-red-alexa-home-skill, browsers: safari and chrome), read all your documentation and solved issues on git ... no luck. Would be nice if you have any idea how to fix this problem.
My user on alexa-node-red.bm.hardill.me.uk is alex7799.

Thanks and regards

**Comment by hardillb** [comment]
OK, 

Before following these instructions make sure you have access to the Node-RED logs (not the browser console logs).  Depending on how you are running Node-RED will depend where they are, if you run Node-RED as a service then the logs end up in the system logs and can be viewed with the `node-red-log` command. If you are starting it manually then it will be output to the console.

1. Make sure you are actually running with version 0.1.17 (check with the pallet manager)
2. Stop Node-RED
3. Edit the alexa.js file in the node, remove the `//` from the start of line 327
4. Restart Node-RED
5. Delete all the alexa nodes including the config node that contains your username and password. (you can list the config nodes from the menu)
6. Drag a new node on to the canvas and add a new config node with your username and password, when you hit Done, wait a moment before checking on the device dropdown.

If the drop down list is not populated please upload the Node-RED log to here so I can see the error output.

Also please run the following command from the same machine that is running Node-RED, replacing [password] with your password and add the output here.

```curl https://alex7799:[password]@alexa-node-red.bm.hardill.me.uk/api/v1/devices```

**Comment by hanpude** [comment]
Excellent Sir,

this answer already solved my problem. The second I saw the curl line, I knew what the problem was.
I used a ':' (colon) in my password, in another try I used an '@'  which obviously broke the connect to the device URL. A username and password without "special" characters immediately worked.
Thank you very much for the fast reply and for this code.

Cheers
Hans

**Comment by hardillb** [comment]
hmm, special chars in the password should work, I'll try and look at that later.

But glad things are working for you now
