### ISSUE TITLE
Alexa home skill for Node RED

### ISSUE THREAD

**Issue by GOR1DON** [hardillb/node-red-contrib-alexa-home-skill#22]
H,

I believe I have set up node Red correctly to interact with Alexa but my Alexa node is not showing as connected. I set up an account with new devices and Alexa can see them. Node red is running on my raspberry pi I'm obviously missing something here but can't understand what.

Help!

**Comment by hardillb** [comment]
Just saying it doesn't work really doesn't give me much to go on.

1. What is your username on the system?
2. What browser are you using?
3. Is there any output in the Node-RED logs?
4. What  version of the node-red-contrib-alexa-home-skill do you have installed?
5. When did you create your account?

**Comment by GOR1DON** [comment]
As you can tell I'm a little new to this. I have added the Node red skill
to the Echo Dot and installed the latest node versions to Node red that is
running on my Raspberry Pi 3. 'm following the process outlined here
https://alexa-node-red.bm.hardill.me.uk/docs#linkAccount. Is this correct?
I don't have access to the system at the moment but the info I do have is
my user name is gor1don, I'm using Chrome as the browser. Where can I get
the logs? I only installed the home skill at the weekend so assume its the
latest as was the account opening.

Rgds

Gordon

**Comment by GOR1DON** [comment]
Update: It's fixed! I had some other flows that were interfering

Rgds

Gordon

**Comment by hardillb** [comment]
Cool, would love to know what was stopping it working in case others hit it.

For future ref, assuming you have installed using the install/upgrade script from the node-red website the command `node-red-log` will tail the logs from the running service instance of node-red

**Comment by GOR1DON** [comment]
Not sure what was stopping it. May have been some MQTT stuff. I'll let you
know if I find anything
