### ISSUE TITLE
Not responding

### ISSUE THREAD

**Issue by smadds** [hardillb/node-red-contrib-alexa-home-skill#23]
Just set up an account on your server (simon.maddox),  created a device (kitchen downlights) and added skill to Alexa inc authorising account. I have loaded the npm into node-red and configured it - including selecting the device and setting to auto respond.

If I command Alexa, she replies (after about 5sec pause) "Sorry, kitchen downlights is not responding"

Any ideas?

**Comment by hardillb** [comment]
AWS seams to have restarted the instance that has the broker and DB on a new IP address. I'm trying to work out what's going on.

**Comment by smadds** [comment]
I could see you're having issues with the server - good luck!

Maybe an Elastic IP would help if it happens again?

**Comment by hardillb** [comment]
Temp fix in place, but any new accounts or device changes since Sept 29th have been lost. Please recreate your account/devices and remove and re-add the skill to Alexa and do discovery again.

**Comment by smadds** [comment]
Have re set-up account & links, but still getting the same error back from Alexa. It knows the device exists (e.g. if I say "Alexa turn kitchen lights on" it replies "Kitchen Downlights isn't responding")

**Comment by hardillb** [comment]
Have you restarted Node-RED as well? 

Does the Kitchen Downlights node have  a green dot and connected next to it?

Is the  Auto Acknowledge box ticked or unticked?

**Comment by smadds** [comment]
I think I had a rogue node (artnet-out) that was not registering properly. Removing that fixed the issue. Thanks for your quick responses.

**Comment by hardillb** [comment]
cool

I had a play with the artnet nodes a while ago for a project, but they weren't the best. There may be a slightly tweaked version in my repo list. I also got upset that the spec had co-opted a public IP range.
