### ISSUE TITLE
increase and decrease temp requests

### ISSUE THREAD

**Issue by ins4neuk** [hardillb/node-red-contrib-alexa-home-skill#24]
I've set up a device and when i say set "alexa, set device to 20 degrees" it works fine but when i say "alexa increase/decrease device by 2 degrees" it asks which device, i repeat the name and it works fine. but every time i have to say the name twice.

any suggestions

**Comment by hardillb** [comment]
Unfortunately all that is handled by Amazons voice recognition system and never gets anywhere near my code.

The best I can suggest is you use the Alexa phone/tablet app to go in and help train the voice recognition model by pointing out what it got right/wrong.

**Comment by ins4neuk** [comment]
No worries will do. i already have hive on there and wasn't sure if it was conflicting.

i saw you were working on an google home style addon as well, any updates on that as i couldn't find the thread where you mentioned it originally!

**Comment by hardillb** [comment]
The Google Home version got put on the back burner for a little while as I've been busy with a few things including moving the Alexa version to AWS. I hope to pick it up again over the Christmas period if I get time.

**Comment by ins4neuk** [comment]
awesome, hope you do as i would love to use the home like i can with the alexa as out the box the home does more for me but i like the ability to integrate anything i want with alexa using your skill.

thanks again for the updates.
