### ISSUE TITLE
How can we manage control options for media devices?

### ISSUE THREAD

**Issue by vworp** [hardillb/node-red-contrib-alexa-home-skill#25]
I'm been messing with node-red-contrib-lgtv, to control an LG smart TV. I've successfully built up a number of flows to turn the tv on/off, increment/decrease the volume and increment/decrease the channel. 
When I create a device at https://alexa-node-red.bm.hardill.me.uk/devices , "TV" for example, I can set it's actions to turn on, turn off, increment percentage and decrement percentage. On/off, Volume +/- accordingly. Not really anywhere for the channel +/-.
If I try to split the controls over three devices, TV, TV volume, Channel, Alexa doesnt recognise the two new devices. Possibly "TV volume" is too close to TV and Alexas built in volume control. Strangely "Channel", is "command not recognised on this device."

**Comment by hardillb** [comment]
You can't yet as I've not had time to implement the AV controls yet.

**Comment by vworp** [comment]
I'm in no rush for them, I was just messing about with some practice flows.
Thanks for the work so far.
