### ISSUE TITLE
All devices offline/undiscoverable

### ISSUE THREAD

**Issue by bobMuk** [hardillb/node-red-contrib-alexa-home-skill#27]
I've had the skill running nicely for a few months, then this weekend everything gets the "device not responding" response and appears offline in the alexa app.  In NodeRed on my Pi all devices show the green dot and "connected".  I tried deleting all devices in the alexa app and rescanning - it doesn't discover anything.  Next I tried deleting the skill and then re-adding it (going through the link account page again) but it still doesn't discover anything.
If I login to alexa-node-red.bm.hardill.me.uk all of my devices are present.
I'm positive that nothing's changed at my end, so no idea why everything's just stopped working.  Have I missed anything?

**Comment by hardillb** [comment]
When did you set up your account?
I'm going to guess it was about 3 months ago?

There is a problem with Amazon doing oAuth token refresh, as a work around I've set token expirary to 100 years, but they used to be 90 days. I updated a bunch of existing accounts to the new date but some may have got missed.

What is your username on the system?

**Comment by hardillb** [comment]
I've reset the expiry date for the token to November 2117, try now

**Comment by bobMuk** [comment]
Thanks Ben, spot on - all appears to be working again. Cheers again for the work you put into this :)
