### ISSUE TITLE
Device is not responding to Alexa voice command.

### ISSUE THREAD

**Issue by edpvic** [hardillb/node-red-contrib-alexa-home-skill#28]
Hello Ben,

I follow you detailed procedure to install a node-red-contrib-alexa-home-skill using Manage Palette , Of course,  an account was created.  I added a device for testing...Alexa discovery the device without issues, but when I try to turn on the light using Alexa voice command (Alexa, turn bedroom on) Alexa respond "ok" but the light doesn't turn on.  Using the Amazon Alexa apps  version 2.2.886.0 (Smart Home), manually I can turn on and off the light.
I don't know if I am doing something wrong, can you give a me tips?

I'm using:
Amazon Echo (2nd generation)
Raspberry PI3 as server. (Stretch Lite)
Node-Red vesion version: v0.17.5
Node.js  version: v6.12.0
Linux 4.9.59-v7+ arm LE
Node-Red Alexa Home Skill Bridge accound is: lisvic

I will appreciate your help.
Thanks a lot!
Victor

**Comment by hardillb** [comment]
If the Alexa is replying with OK then the request has made it to the
Node-RED instance. So you will need to explain/show how you have wired that
node to what ever is controlling the light


http://www.hardill.me.uk/wordpress
http://www.twitter.com/hardillb
http://www.flickr.com/photos/hardillb

**Comment by edpvic** [comment]
Hello,

Thanks for your replay!!

The node red flow is wired as follow:

[{"id":"9d682500.744ca8","type":"ui_switch","z":"c4dbfa86.85fe58","name":"On/Off Light-Switch 01:","label":"Floor Lamp (Rec3):","group":"bc5b5e2f.93304","order":2,"width":"5","height":"1","passthru":false,"decouple":"false","topic":"","style":"","onvalue":"1","onvalueType":"str","onicon":"","oncolor":"","offvalue":"0","offvalueType":"str","officon":"","offcolor":"","x":486.33331298828125,"y":254.0281524658203,"wires":[["74817edf.00219","55b796ba.d1b778"]]},{"id":"74817edf.00219","type":"mqtt out","z":"c4dbfa86.85fe58","name":"Home/Light-SW01/OnOff","topic":"Home/Light-SW01/OnOff","qos":"1","retain":"","broker":"faa9385.50725c8","x":909.4046440124512,"y":247.59954795241356,"wires":[]},{"id":"7dacbd54.bdfe24","type":"mqtt in","z":"c4dbfa86.85fe58","name":"Home/Light-SW01/OnOff","topic":"Home/Light-SW01/OnOff","qos":"1","broker":"faa9385.50725c8","x":1201.2261428833008,"y":245.71496066451073,"wires":[["a689c6c3.ffc258"]]},{"id":"a689c6c3.ffc258","type":"debug","z":"c4dbfa86.85fe58","name":"On/Off Light-SW01 from ESP","active":true,"console":"false","complete":"payload","x":1508.1804504394531,"y":245.99618911743164,"wires":[]},{"id":"55b796ba.d1b778","type":"debug","z":"c4dbfa86.85fe58","name":"","active":false,"console":"false","complete":"false","x":867.1662940979004,"y":189.69696044921875,"wires":[]},{"id":"490ff2fd.c4331c","type":"change","z":"c4dbfa86.85fe58","name":"","rules":[{"t":"change","p":"payload","pt":"msg","from":"true","fromt":"bool","to":"1","tot":"str"},{"t":"change","p":"payload","pt":"msg","from":"false","fromt":"bool","to":"0","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":357.64453125,"y":165.8046875,"wires":[["74817edf.00219"]]},{"id":"fed501c5.20b7a","type":"debug","z":"c4dbfa86.85fe58","name":"From Alexa","active":true,"console":"false","complete":"true","x":353.640625,"y":109.1796875,"wires":[]},{"id":"d9332698.713638","type":"alexa-home","z":"c4dbfa86.85fe58","conf":"647364ef.0686ac","device":"11429","acknoledge":true,"name":"bedroom","topic":"bedroom lamp","x":113.95237731933594,"y":165.9047622680664,"wires":[["fed501c5.20b7a","490ff2fd.c4331c"]]},{"id":"bc5b5e2f.93304","type":"ui_group","z":"","name":"Ligth Interruptor","tab":"b788aea7.2c3b9","disp":false,"width":"6"},{"id":"faa9385.50725c8","type":"mqtt-broker","broker":"localhost","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":15,"cleansession":true,"willQos":"0","birthQos":"0"},{"id":"647364ef.0686ac","type":"alexa-home-conf","z":"","username":"lisvic"},{"id":"b788aea7.2c3b9","type":"ui_tab","z":"","name":"Light On/Off Switch","icon":"lightbulb_outline","order":6}]

Attached, also you can find an image of the nodes and the logs (debug) only when is performed an action to turn on/off ordered from Alexa apps...no results were observed from voice commands.

![node-red flow image](https://user-images.githubusercontent.com/35175684/34651241-9baf7058-f39b-11e7-9afc-cab2d4938ada.png)

Please let me know if you need additional (specific) information.

Thanks a lot!

**Comment by hardillb** [comment]
So it looks like your MQTT endpoint expect "0" or "1" to turn the light off/on respectively and the Alexa node is outputting `true` for on and `false` for off (`msg.payload` field) so you will need to convert the `msg.payload` to match what the MQTT endpoint needs.

This is not a problem with the node so I'm going to close this issue.

**Comment by edpvic** [comment]
Sorry, this is the right image!!
![node-red flow image](https://user-images.githubusercontent.com/35175684/34651400-e5237b88-f39d-11e7-8ba4-c62bfdf9f83e.png)

**Comment by edpvic** [comment]
Yes, but I added a change node to replaced true by "1" and false by "0".  I'm confused...why it is working the the apps and not with the voice command??

Thks a lot!!

**Comment by hardillb** [comment]
No idea with out knowing way more about what ever you have on the end of the MQTT connection or what the dashboard-ui switch is outputting or what's in the change node.

But either way it's not a problem with the alexa node so this is not the right place to work it out

**Comment by edpvic** [comment]
Ok, just one last question ... Should I expect a similar message from the voice command like the one generated with the Alexa apps?

 For example:

1/7/2018, 1:12:17 PMnode: From Alexa
Home/Light-SW01/OnOff : msg : Object
object
topic: "Home/Light-SW01/OnOff"
name: "bedroom"
_messageId: "e44ea824-e689-4fe3-9df7-69ff63106e75"
_applianceId: "11429"
_confId: "647364ef.0686ac"
command: "TurnOffRequest"
extraInfo: object
payload: false
_msgid: "175741e5.1681ee"

Thanks a lot for you support!!

**Comment by hardillb** [comment]
They are identical (apart from the `_messageId` which should be unique to every request)
