### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by thps1990** [hardillb/node-red-contrib-alexa-home-skill#30]
Hi Guys,

since a few hours i´m getting no connection to the Server. After Login to https://alexa-node-red.bm.hardill.me.uk/login, the following error occurs:

> nginx error!
> The page you are looking for is temporarily unavailable. Please try again later.
> Website Administrator
> Something has triggered an error on your website. This is the default error page for nginx that is distributed with the Amazon Linux AMI. It is located at /usr/share/nginx/html/50x.html
> 
> You should customize this error page for your own site or edit the error_page directive in the nginx configuration file /etc/nginx/nginx.conf.

sincerely thps

**Comment by hardillb** [comment]
Fixed, a Docker host had filled it's disk with logs, shouldn't happen again.

**Comment by thps1990** [comment]
Thanks a lot!

Am 14.01.2018 9:09 vorm. schrieb Ben Hardill <notifications@github.com>:

Fixed, a Docker host had filled it's disk with logs, shouldn't happen again.
