### ISSUE TITLE
alexa-home-conf not registered

### ISSUE THREAD

**Issue by riphill** [hardillb/node-red-contrib-alexa-home-skill#31]
I was attempting to integrate this skill with my emonpi energy monitoring device.  This is built on a raspberry pi and as such runs a version of debian Jessie.  I've set my node red version to do some other MQTT integration so would like to add the skill to it but I suspect the version may not be compatible with the node - I did upgrade to v0.15.3 but this hasn't improved things.

The install goes well enough, either by command line (the pallet item not does appear if installed by command line) - if installed via the GUI the Alexa items show up until you reload the browser.

I recall seeing some ouput related to an import of hoek, but I can't recall where now, probably me starting on the command line.

I offer the following if it sheds an light on the issue...

From journalctl:

$ journalctl -f -u nodered -o cat
16 Feb 19:14:54 - [info] Added node types:
16 Feb 19:14:54 - [info]  - node-red-contrib-alexa-home-skill:alexa-home-conf : SyntaxError: Use of const in strict mode.
16 Feb 19:14:54 - [info]  - node-red-contrib-alexa-home-skill:alexa-home : SyntaxError: Use of const in strict mode.
16 Feb 19:14:54 - [info]  - node-red-contrib-alexa-home-skill:alexa-home-resp : SyntaxError: Use of const in strict mode.
16 Feb 19:29:02 - [warn] Credential type 'alexa-home-conf' is not registered
16 Feb 19:29:02 - [info] Stopping modified flows
16 Feb 19:29:02 - [info] Stopped modified flows
16 Feb 19:29:02 - [info] Waiting for missing types to be registered:
16 Feb 19:29:02 - [info]  - alexa-home-conf
16 Feb 19:29:02 - [info]  - alexa-home

**Comment by hardillb** [comment]
You need to upgrade NodeJS not node-red (but you should probably upgrade to at least node-red 0.17.5 as well)

**Comment by hardillb** [comment]
Use the script on the Node-RED website, this will upgrade both Node-RED and the underlying NodeJS to a supported version

**Comment by riphill** [comment]
I ran update-nodejs-and-nodered and I'm up to version 0.18.3 - I'm not sure about the NodeJS or NPM part.  The upshot of that is that it all seems to work, I can connect in nodered and get the device listing.  Alexa can discover the devices - but ask her: "Alexa, turn on living room light" - she claims no knowledge "sorry I didn't find living room light" (It's an echo dot gen 2).  I'll probably have to play about with it a bit more, I have an input node with a debug output if anything comes through - but the issue raised on this ticket is resolved.

**Comment by hardillb** [comment]
Try renaming your device to "Livingroom Light"

**Comment by riphill** [comment]
Thanks, I gave that a go.  Oddly the echo dot will not discover new devices, only the web client will - and then the dot doesn't seem to know about them.  I suspect this is the root of the issue, which makes me think it might be firewall related, but I don't know how it does discovery.

**Comment by riphill** [comment]
Believe it or not I called amazon support about the discovery issue, and I went through a fairly tedious, "reset this", "try this procedure".  In the end I removed all discovered devices - totally reset the echo dot (not expecting anything to change) - and re-ran discovery - discovery worked straight away.   So it all works.   In part both annoying and good at the same time...!
