### ISSUE TITLE
Amazon Alexa skill fails to enable

### ISSUE THREAD

**Issue by kdubovenko** [hardillb/node-red-contrib-alexa-home-skill#32]
Hi Ben,

I think there is a chance that this is an AWS issue but I figured I'd notify you anyway. Alexa wasn't responding to my requests earlier so as part of troubleshooting I decided to disconnect and reconnect the skill but by doing that got the following warning. 
![img_0641](https://user-images.githubusercontent.com/6765318/36931084-d541dd9a-1e63-11e8-96fa-e1612515ad4e.JPG)
So looks like the node-red skill is not able to connect, can't tell from the message what the error is.

Thanks for your time,

-Konstantin

**Comment by Crypti-x** [comment]
same

**Comment by hardillb** [comment]
Should be back, last backup was the 24th so new accounts/devices may need to be recreated

**Comment by hardillb** [comment]
@fulcrumEFX Don't use closed issues to report new outages, it makes tracking things a pain. It's back up

@swilson86 No, and I have no intention of documenting it any more than it is

**Comment by fulcrumEFX** [comment]
@hardillb OK, sorry. I didn't want to open a new issue because usually these things are fixed pretty quickly, just wanted to let you know.

But next time I'll open a new one.
