### ISSUE TITLE
Maybe this is a possibility?

### ISSUE THREAD

**Issue by summer69guy** [hardillb/node-red-contrib-alexa-home-skill#33]
Hi,

I am wondering if this npm package can tel mode red which echo I am talking too? I have 6 echo in my house.

I can do a workaround this with z wave power mesurement node... but I need two delays with a counter

-one of 2 seconds...because of the delay of z waves.  Then it change a count to value of ‘’1’’
-and then.. one of 4 secs ( to change the counter back to 0 when power is returned to initial stated ) .... so when the counter is set to one it tells me Alexa I am talking to this particular echo. If the counter is set back to 0 it tells me this particular echo is back to ‘’normal’’

This solution is not optimal because of the delays...and the complexity of putting a counter in the middle ...and sometime is does not work because of the delayq (it world 95% of time)

**Comment by summer69guy** [comment]
Sorry my navigator had a bug. Was not able to correct my 1sst post.
——

So... like that I am able to say: Alexa turn on plex ‘’ and depending of where I am in the house , it will open plex on my living room tv, or on my bedroom tv.

This is a workaround for the poor room integration of Alexa at this time...


So..I was wondering is this plugin could, in a near future have a node that tells which echo is being used ? Thank you

I am using homeseer system btw, with node red.

**Comment by summer69guy** [comment]
I did mention the flooding à the z wave network with my present workaround... so if you guys could had a feature like this , it would be awesome

**Comment by hardillb** [comment]
No it is not possible to identify the Echo device that is making the request, that information is not available with the Smart Home Skill API
