### ISSUE TITLE
Minor issue on switch

### ISSUE THREAD

**Issue by swilson86** [hardillb/node-red-contrib-alexa-home-skill#34]
I have a group of 3 devices that stopped working. I can turn them on with the "Alexa All Bar Lights On" command, but with "Alexa All Bar Lights Off" she says "All Bar Lights doesn't support that." Strange. I can individually turn them all off. 

Tried deleting the devices both from Node-Red and within your registration page, then asking Alexa to discover devices. Then reinstalled everything and Alexa discovered the command. But same problem... can never turn them off, just on. Ideas?

**Comment by hardillb** [comment]
Not really.

My only question would be have you marked the devices as "SWITCH" or "LIGHT" at the bottom of the device editing dialog? Given that the name is "All Bar Lights" I wonder if the Amazon matching is getting confused

**Comment by swilson86** [comment]
Duh! I didn't tick the "Off" option during registration with your site. As a side note... it doesn't seem to make any difference whether I select Switch or Light in the device editing dialog. It works even when nothing is ticked. That total section seems to be undocumented.
