### ISSUE TITLE
Service down due to DNS

### ISSUE THREAD

**Issue by hardillb** [hardillb/node-red-contrib-alexa-home-skill#36]
My ISP have screwed up my broadband for over a week so my DNS has been down that long and all the entries in the secondary are now expired which means that none of the machines needed for the service can be resolved.

This will be fixed as soon as my broadband is back up, but there is nothing I can do until then.

This problem will be tracked from this [issue](https://github.com/hardillb/node-red-alexa-home-skill-web/issues/58) on the web app project

**Comment by geekypenguin** [comment]
Anything we can do to help?
Happy to lend you server space on a fixed ip until yours it back running

**Comment by hardillb** [comment]
Unfortunately it's the primary DNS server that is down and it's a full DNSSEC setup so moving it will take a while. There is an engineer (the second this week) due in the morning, it will get fixed or they'll move me back to ADSL which works (unlike the last FTTC port in the cab...)

**Comment by hardillb** [comment]
DNS Server is back up. Everything should work now
