### ISSUE TITLE
Thermostat works via voice but not in Alexa app

### ISSUE THREAD

**Issue by lawrence-jeff** [hardillb/node-red-contrib-alexa-home-skill#37]
Can't figure this out, I have 2 smart locks working fine but when I attempt to add a simple temp sensor I can't get it to work - it works fine via a voice request, but the device in the phone app shows a thermostat icon but doesn't display the temp (selecting the device takes you to the edit screen.) On my nest it shows the current temperature along with set point and adjustment buttons.

Thinking maybe a temp sensor (without the adjustment options) isn't valid to Alexa I tried to make it a full thermostat device hoping that would make it work but still no luck in the app.

Device is setup like this (options selected)
C/F:  
+°C/F:
 -°C/F:   
Query Set Point:    
Query Current Temp:   
THERMOSTAT

Simple response that always replies with
 msg.extra = {
    "temperatureReading": {
        "value": 25.11
    },
      targetTemperature: {
        value: 25.0
    },
        temperatureMode: {
        value: "AUTO"
    },
    "applianceResponseTimestamp": new Date().toISOString()
};
msg.payload = true;
return msg; 

Voice commands work (can query set point and current temp) but selecting the icon in the Alexa app doesn't show any of these values (like a NEST thermostat does)

Any advice?

**Comment by hardillb** [comment]
Nope, only thing I can think is that the NEST kit is using v3 of the API which supports async notifications. But if it's working for voice I can see no reason why it wouldn't work from the app.

**Comment by lawrence-jeff** [comment]
Do any temperature related devices show a UI for you in the app? I notice your example in the documentation has a temp sense/adjust options but wasn't sure if you focus on voice functionality only. Smart locks and on/off devices trigger the app UI , the issue seems to be specific to the thermostat device.

**Comment by hardillb** [comment]
I have an example that implements all the possible thermostat features and it doesn't show any controls in  the app. There is no way to specify anything as voice/app specfic

As I said this is most likely a v2 vs v3 API thing so there is not much I can do about it at the moment.

**Comment by NorthernMan54** [comment]
@lawrence-jeff I can confirm that a simple temperature sensor with V3 of the Alexa api does not show the temperature in the app as well, just the edit screen. This is an amazon limitation in their app.
