### ISSUE TITLE
Skill Amazon

### ISSUE THREAD

**Issue by Leprechaun91** [hardillb/node-red-contrib-alexa-home-skill#4]
Hey,

I know Amazon still needs to approve but is there maybe a opportunity to get the code and do it on my own?

**Comment by hardillb** [comment]
The code is on github, but it is a complex collection of parts. I do not have time to guide people through setting it up. You will just have to wait

**Comment by hardillb** [comment]
The skill has now gone live in the US, UK and Germany if you want to have a play,
