### ISSUE TITLE
Amazon Skill for French

### ISSUE THREAD

**Issue by ncarlier** [hardillb/node-red-contrib-alexa-home-skill#40]
Hello,

before all thanks a lot for this amazing service. I'am a fan of Node-RED and your bridge is just perfect.
I recently changed to the French Amazon store. And unfortunately, the skill is not available.
Please, can you activate the French region for this skill?

**Comment by ncarlier** [comment]
Do you have any idea how long it takes to pass the Amazon validation process?

**Comment by hardillb** [comment]
No

**Comment by hardillb** [comment]
Amazon have now stopped messing about and approved the entry in the French store (even if they did respond in Japanese)

**Comment by ncarlier** [comment]
Good news!

Arigatōgozaimashita ("Thanks" in ... not French ;) )
