### ISSUE TITLE
Italian language, please!

### ISSUE THREAD

**Issue by woody4165** [hardillb/node-red-contrib-alexa-home-skill#43]
Hi and thanks for the hard work.

How can I contribute to get Italian language for the Alexa skill?

Thanks

**Comment by hardillb** [comment]
Italian is not in the list of available languages from Amazon for Alexa Smart Home Skills at the moment.

I can provide the text that will need to be translated when Amazon add Italian support if you want, then it's ready.

If you want to translate the actual node it's self then you can have a look at the file in [alexa.html](https://github.com/hardillb/node-red-contrib-alexa-home-skill/blob/master/locales/ja/alexa.html) in the `locales/ja` folder in the source and create a similar one based on the [alex.html](https://github.com/hardillb/node-red-contrib-alexa-home-skill/blob/master/alexa.html) in the root of the project.

**Comment by woody4165** [comment]
Hi 

Alexa and Amazon Echo are not officially available in Italy, but they are testing it and I'm one of the lucky guy that's why you don't find as available languages, but from the Alexa app I can see lots of Italian skills and also international ones (like Home Assistant, Netatmo and others).

Yes, please, if you can share the text to be translated I will be happy to do it.

I will take a look at the `locales/ja/alexa.html`

Thanks

**Comment by hardillb** [comment]
Please translate the following strings:

> An Alexa Home Skill for use with Node-RED

> Node-RED is a tool for wiring the Internet of Things, this skill allows you to use Alexa to trigger Node-RED flows. 
> 
> Node-RED flows can control many different home device such as Belkin WeMo and Philips Hue Lights or any number of home brew devices and services. A list of Node-RED nodes that can be invoked via the Node-RED Alexa Home Skill node can be found at http://flows.nodered.org
> 
> To use this skill you must have an instance of Node-RED and install the node-red-contrib-alexa-home-skill node, this can be installed on your own device or on a cloud service. For more details about Node-RED and how to install it see here http://nodered.org. Details of how to install and configure node-red-contrib-alexa-home-skill can be found here https://alexa-node-red.bm.hardill.me.uk/docs

> - Alexa, turn on kitchen light
> - Alexa, set bedroom to 24 degrees
> - Alexa, dim living room light

**Comment by woody4165** [comment]
Here it is:

Un’Alexa Home Skill da usare con Node-RED

Node-RED e’ uno strumento per  connettere l’Internet of Things, questa skill consente di utilizzare Alexa per attivare i flussi di Node-RED.

I flussi di Node-RED possono controllare dispositivi domestici come Belkin WeMo e Philips Hue Lights o svariati dispositivi e servizi fatti in casa. Un elenco di nodi Node-RED che possono essere richiamati tramite il nodo Node-RED Alexa Home Skill e’ disponibile su http://flows.nodered.org

Per utilizzare questa skill e’ necessario disporre di un'istanza di Node-RED e installare il nodo node-red-contrib-alexa-home-node, che puo’ essere installato sul proprio dispositivo o su un servizio cloud. Per maggiori dettagli su Node-RED e su come installarlo, vedere qui http://nodered.org. I dettagli su come installare e configurare node-red-contrib-alexa-home-skill possono essere trovati qui https://alexa-node-red.bm.hardill.me.uk/docs

Alexa, accendi la luce della cucina
Alexa, imposta la camera da letto a 24 gradi
Alexa, regola l’intensita’ della luce del soggiorno

**Comment by hardillb** [comment]
I've found where Amazon have hidden the Italian language settings and I've submitted it for approval. I'll close this  issue when it's been approved

**Comment by woody4165** [comment]
Great!
Thanks.

**Comment by hardillb** [comment]
Italian should be live node
