### ISSUE TITLE
unable to link Node-RED at this time

### ISSUE THREAD

**Issue by garywilson4** [hardillb/node-red-contrib-alexa-home-skill#44]
getting the above message at a loss what to do

**Comment by hardillb** [comment]
What is your username?

**Comment by hardillb** [comment]
Also some context would be useful, is this the first time you have tried to link the skill or are you trying to relink it later.

**Comment by garywilson4** [comment]
username is Garywilson4 and i'm trying to re link it basically i had to re-install my pi due to some security issue and now can't get this to work

**Comment by hardillb** [comment]
Try again.

**Comment by garywilson4** [comment]
Thanks whatever you did fixed it and thank you for your quick reply

**Comment by garywilson4** [comment]
sorry to be a pain but i'm getting this message Error: connect ECONNREFUSED 34.240.81.189:8883

**Comment by hardillb** [comment]
That's normal ignore it, it will reconnect on port 1883 afterwards

**Comment by garywilson4** [comment]
ah ok thanks again

**Comment by geniomatto** [comment]
Ciao a tutti... anch’io ho lo stesso problema di error ECONNREFUSED... si connette x 4-5 secondi e poi da errore... poi si connette di nuovo e dopo da subito errore... come potrei risolvere? Che tipo di errore è?

**Comment by hardillb** [comment]
@geniomatto I'm sorry English only for issues please, also please open a new issue this one is closed

**Comment by jezza5150** [comment]
Hi Ben, Great App but Im also "Error: connect ECONNREFUSED 34.240.81.189:8883" my user is "casualsix" any help would be apprciated.

**Comment by hardillb** [comment]
@jezza5150  Please read the issue before jumping in with "me too". The discussion of that message is already covered.

This is a closed issue, and will not be reopened
