### ISSUE TITLE
Translate skill to Spanish

### ISSUE THREAD

**Issue by orxaz** [hardillb/node-red-contrib-alexa-home-skill#45]
Hi.

I would like to translate the skill to Spanish.

**Comment by hardillb** [comment]
If you can translate the following it will speed things up:

--------------

An Alexa Home Skill for use with Node-RED

----------

Node-RED is a tool for wiring the Internet of Things, this skill allows you to use Alexa to trigger Node-RED flows.

Node-RED flows can control many different home device such as Belkin WeMo and Philips Hue Lights or any number of home brew devices and services. A list of Node-RED nodes that can be invoked via the Node-RED Alexa Home Skill node can be found at http://flows.nodered.org

To use this skill you must have an instance of Node-RED and install the node-red-contrib-alexa-home-skill node, this can be installed on your own device or on a cloud service. For more details about Node-RED and how to install it see here http://nodered.org. Details of how to install and configure node-red-contrib-alexa-home-skill can be found here https://alexa-node-red.bm.hardill.me.uk/docs

-------

Alexa, turn on kitchen light

Alexa, set bedroom to 24 degrees

Alexa, dim living room light

**Comment by orxaz** [comment]
Hi.

Done!

EN - An Alexa Home Skill for use with Node-RED
ES - Un Skill de Alexa Home para usar con Node-RED

EN - Node-RED is a tool for wiring the Internet of Things, this skill allows you to use Alexa to trigger Node-RED flows.
ES - Node-RED es una herramienta para enlazar el Internet de las Cosas (IoT), este skill te permite usar Alexa para lanzar flujos Node-RED.

EN - Node-RED flows can control many different home device such as Belkin WeMo and Philips Hue Lights or any number of home brew devices and services. A list of Node-RED nodes that can be invoked via the Node-RED Alexa Home Skill node can be found at http://flows.nodered.org
ES - Los flujos Node-RED pueden controlar muchos dispositivos domésticos diferentes como bombillas Belkin WeMo y Philips Hue o cualquier dispositivo y servicio artesanal o casero. Puedes encontrar una lista de los nodos Node-RED que pueden ser invocaddos a través del Skill Alexa Home Node-RED en http://flows.nodered.org

EN - To use this skill you must have an instance of Node-RED and install the node-red-contrib-alexa-home-skill node, this can be installed on your own device or on a cloud service. For more details about Node-RED and how to install it see here http://nodered.org. Details of how to install and configure node-red-contrib-alexa-home-skill can be found here https://alexa-node-red.bm.hardill.me.uk/docs
ES - Para usar este skill debes tener una instancia de Node-RED e instalar el nodo node-red-contrib-alexa-home-skill, este puede ser instalado en tu propio dispositivo o en un servicio cloud. Para más detalles sobre Node-RED y de cómo instalarlo consulta http://nodered.org . Puedes encontrar detalles sobre cómo instalar y configurar node-red-contrib-alexa-home-skill en https://alexa-node-red.bm.hardill.me.uk/docs

EN - Alexa, turn on kitchen light
ES - Alexa, enciende la luz de la cocina

EN - Alexa, set bedroom to 24 degrees
ES - Alexa, pon la habitación a 24 grados

EN - Alexa, dim living room light
ES - Alexa, atenúa la luz del salón

**Comment by hardillb** [comment]
I've sent the update off to Amazon to approve, this can take a while.

I'll close the issue when it's live

**Comment by orxaz** [comment]
Thanks!

**Comment by orxaz** [comment]
Hi @hardillb 

Do you know how long can take Amazon to approve this?
Is normal them to take 2 weeks or more?

Thanks!

**Comment by hardillb** [comment]
Yes this is normal, mainly because they always reject skills based on grammar in the description and usually multiple times and they only point out one error at a time

**Comment by orxaz** [comment]
Ok, hope them aprove it soon, can't wait to test!

Thanks!

**Comment by hardillb** [comment]
Should be live now

**Comment by orxaz** [comment]
Many thanks!
