### ISSUE TITLE
GetLockStateRequest works from app but not via voice

### ISSUE THREAD

**Issue by bioego** [hardillb/node-red-contrib-alexa-home-skill#47]
Hi,
I've set up a few lock sensors in node-red and I want to let Alexa read me their status as if they were smartlocks. I've configured one of the sensors in my devices on your site as a smartlock with lock/unlock and getlockstate features enabled.

In my flow I have the AlexaHome node set to this device, a function to properly set the msg.extra lockstate info and the AlexaHomeResponse node.

When I discover the device with Alexa and access it from the app (by clicking on its name) I can see its status correctly (closed or opened) so I guess the flow in node-red is working as expected, but if I ask Alexa what's the status of the device it tells me that the function is not available on the device.

Also on Node-Red debug I can see the GetLockStateRequest command being received when I'm accessing the device from the app, while it doesn't receive any command when asked by voice, so it seems something is not working on the Alexa or service side, not on the flow.

By the way I have no issues in getting info from thermostats using you service.

Any pointer to what I'm doing wrong?
Thanks!

**Comment by hardillb** [comment]
If it works from the app then it should work via voice as there is only one code path.

The only thing I can think it might be is the phrase you are using to ask about the status. Also do you have any similarly named devices it could be getting confused with?

**Comment by bioego** [comment]
Hmm...it may be that the voice control is not fully implemented in italian yet. I tried various sentences and got nowhere. There's also no other devices with similar name, and the alexa app shows it recognizes the correct word.

**Comment by hardillb** [comment]
I'm going to close this if there is no update, as I said from the skills point of view there is no difference between clicking on the app and asking via voice.

**Comment by bioego** [comment]
Sorry for the delay: I've contacted Amazon support and it seems indeed that the voice support for smart lock is not yet fully implemented in italian, so I'm closing the issue since it's not due to anything not working in the skill itself.
Thanks!
