### ISSUE TITLE
Device discovery problem

### ISSUE THREAD

**Issue by ashish8284** [hardillb/node-red-contrib-alexa-home-skill#48]
Hi,
I have enabled node red skill in my Alexa account,
I create account & create three devices.
On my raspberry Pi 3B I installed nodered & install nodered Alexa contribute  skill & create three nodes.
I linked my account & successfully link qll three devices in nodered.

finally I applied discover new device command to my echo dot but surprisingly it did not discover any device.

Help needed!!!

**Comment by ashish8284** [comment]
Hi,
First of all thanks for prompt response.
User Name - Ashish_8284
Country :- India
Device name :-
       Device 01:- Desk fan
       Device 02:- Desk light
       Device 03:- ac

**Comment by hardillb** [comment]
There is nothing obviously wrong with any of the devices and discovery seems to be working for everybody else.

I see you created the account back in August, so has this worked before or is this the first time you've tried? 

If this has worked before what else have you changed?

**Comment by ashish8284** [comment]
at the time of account creation I had taken trial by creating one device & at that time it works fine.

Since then I never used it.
I started use it two days back for my home automation.

while Alexa start discovery i observed error  (ECONNREFUSED) in nodered log on my PI.

**Comment by hardillb** [comment]
The ECONNREFUSED error is normal, it's part of a fallback solution for the broker, it will connect to the alternate endpoint after about 30 seconds. I'm working on a way to hide it.

Discovery is all handled by the cloud, it doesn't interact with the Node-RED component at all.

When you say you didn't use it since August, did you leave the skill linked to your account?

It is also not clear if you have tried unlinking/relinking the skill to the account.

**Comment by hardillb** [comment]
Also how are you trigging discovery? From the app or by asking Alexa to "Discover Devices"?

**Comment by ashish8284** [comment]
Sorry for delayed reply,
i had linked skill to my account all time since account created.
i had disable & enable skill in my alexa account but didn't unlink account.
& try to discover device by applying voice command as well as application.

**Comment by hardillb** [comment]
OK, try unlinking and relinking the skill.

I'm travelling for the rest of the day, I'll try and have another look when I get home

**Comment by ashish8284** [comment]
ok thanks.

**Comment by ashish8284** [comment]
Hi,
I disable node-red skill from alexa app and re connect it plenty of time but not getting success.
finally i have created another account (ashishamu146) and link it with my alexa account & i successfully discover devices from that account & all devices are working as expected.
happy for now.
still my old account(Ashish_8284)not working !!!!!

**Comment by hardillb** [comment]
OK, thanks for letting me know.

It would have been good to get to the bottom of what went wrong with the other account, but you can't link the skill twice.

I'm going to close this for now.
