### ISSUE TITLE
Manually acknowledging TurnOffRequest

### ISSUE THREAD

**Issue by gregma** [hardillb/node-red-contrib-alexa-home-skill#49]
I am trying to use the the 'Alexa Home Response' node to send the acknowledgment, once it has 'successfully' been switched off - but it does not seem to work.  NOTE that the TurnOnRequest works just find and alexa responds with the ding.  In both cases, the device does turn on/off.

Flow:
![flow](https://user-images.githubusercontent.com/3743375/48992918-4a590c80-f0ef-11e8-8e99-b121d20f9ee8.jpg)

Here is the response from the TurnOnRequest that works:
![onresponse](https://user-images.githubusercontent.com/3743375/48992926-56dd6500-f0ef-11e8-8a33-75e7d0651d58.jpg)

Here is the response from the TurnOffRequest that does not work (Alexa reports "Sorry, Bedroom Heater appears to be malfuntioning.")
![offresponse](https://user-images.githubusercontent.com/3743375/48992947-7ffdf580-f0ef-11e8-8921-4a7d73f4f189.jpg)

Any ideas?

-Greg

**Comment by hardillb** [comment]
You need to change the value of `msg.payload` to `true` before sending it to the response node to signify  that the action was successful.

You are currently lettings the value `false` (off) continue through.

**Comment by gregma** [comment]
Of course!  Thank you,  This has been fixed
