### ISSUE TITLE
Node-RED skill

### ISSUE THREAD

**Issue by ddierick** [hardillb/node-red-contrib-alexa-home-skill#5]
Hi,

Thanks for the effort that went into developing this application, people like you make knowledge accessible to all!  I do have a little problem though, I can't seem to find the node-red skill in the skills of the alexa app. Is it not published yet?

**Comment by hardillb** [comment]
Still in the review queue at amazon, assuming you've signed up with a real email address then you'll get an email when it's available.

**Comment by hardillb** [comment]
The skill is now live if you want to have a play
