### ISSUE TITLE
nginx error

### ISSUE THREAD

**Issue by fulcrumEFX** [hardillb/node-red-contrib-alexa-home-skill#53]
the main page is unavailabe

Greetings

**Comment by hardillb** [comment]
I'm stuck with no access to the required SSH keys at the moment, will fix at 5pm UK time

**Comment by hardillb** [comment]
Back up and running

**Comment by sstraus** [comment]
Hi, is down again.

**Comment by hardillb** [comment]
@sstraus please open new issues, back up now
