### ISSUE TITLE
Device is not responding

### ISSUE THREAD

**Issue by agiuliano** [hardillb/node-red-contrib-alexa-home-skill#54]
Hi, from yesterday, when I try to turn on a device using alexa and alexa-home, Alexa keep saying "device-name is not responding".
I've double checked everything, the device is discoverable and my node-red is on and the alexa-home shows connected.
It seems something is wrong in the backend. Is this something you are already aware of?
If not, how can I troubleshoot what's wrong?

**Comment by hardillb** [comment]
I would need your username and the device name to look at the logs

**Comment by hardillb** [comment]
Also when did you create your account and devices?

**Comment by agiuliano** [comment]
username is 'shark' and I only have one device

**Comment by hardillb** [comment]
I can see noting obviously wrong. Have you attached a debug node to the input node to see if the messages are arriving? Also are you using auto acknowledge or doing it manually?

**Comment by hardillb** [comment]
Did you delete and re-add the device on the website at some point?

Anyway the only thing I can suggest at the moment is to try re-linking the skill.

Steps:
 - First up use the Alexa app to unlink the skill
 - Delete the device in the Alexa app
 - add the skill again
 - trigger a device discovery 

You can also remove the input node in Node-RED and then re add it. You should not need to remove the config node.

**Comment by agiuliano** [comment]
I've tried that and now it seems working again. Not sure what happened
