### ISSUE TITLE
alexa not find my component

### ISSUE THREAD

**Issue by neodevit** [hardillb/node-red-contrib-alexa-home-skill#55]
I have  : 

1) install nodered package
--npm install body-parser
--npm install request
--npm install mqtt
--npm install node-red-contrib-alexa-home-skill

2) add dependence on package.json
"dependencies": {
     "node-red-contrib-alexa-home-skill": "*",

3) create account on https://alexa-node-red.bm.hardill.me.uk

4) add component online LED as lamp with on off capatibilities

5) open alexa app on my phone and discovery new device 
alexa find "lampadina1" and i rename as same name "LED" equal to device configured on 
https://alexa-node-red.bm.hardill.me.uk

6) add on nodered flow component LED
connected with pin gpio26

PROBLEM
ask to alexa "turn on led"
but alexa tell me a led is not respond

QUESTION
I have read your sample flow but for sample i have only connect alexa to gpio for try a sample
I have missing a step ?
Thanks for your job and patience

**Comment by hardillb** [comment]
Also in your instructions you don't mention actually linking the skill in the Alexa app. Did you remember to do this?

**Comment by neodevit** [comment]
yes a have installaed a skill alexa and then discovery a new component and alexa find lampadina1 and i change the name in LED.
mi account are NEODEV

**Comment by hardillb** [comment]
You need to run discovery again if you rename the device (because you had to delete the device and recreate it to rename it and as such it's internal ID will have changed)

**Comment by hardillb** [comment]
You will also probably need to make sure the node has the right (with the right new name) selected.

**Comment by neodevit** [comment]
1) deleted LED to app alexa
2) invariated name PROVA to https://alexa-node-red.bm.hardill.me.uk/devices
3) discovery alexa device
4) found Lampadina1
5) not chenge name to alexa
6) change nodered to PROVA 
whith this flow
[{"id":"5fa721f9.9177c","type":"rpi-gpio out","z":"77c3b897.10bb78","name":"LED ALARM 1 : PIN 24","pin":"18","set":false,"level":"0","freq":"","out":"out","x":470,"y":160,"wires":[]},{"id":"20385a38.2eb2b6","type":"alexa-home-resp","z":"77c3b897.10bb78","x":460,"y":120,"wires":[]},{"id":"a45ab7b7.e78cb8","type":"alexa-home","z":"77c3b897.10bb78","conf":"ca138a6a.eb2d48","device":"43903","acknoledge":true,"name":"PROVA","topic":"Led su alexa","x":270,"y":140,"wires":[["20385a38.2eb2b6","5fa721f9.9177c"]]},{"id":"ca138a6a.eb2d48","type":"alexa-home-conf","z":"","username":"neodev"}]
7) ask to alexa open lapadina1
alexa respond to many object with this name
but not is true i not have now other obeject in alexa with this name
8) click lampadina1 to ON into the APP 
response device not respond

---

1) change alexa app name to PROVA
2) try from app but PROVA not respond

I not know the error

**Comment by hardillb** [comment]
1. Do not change the name of devices in the Alexa app, there is no need and it just confuses things.
 2. The Lampadina1 device is nothing to do with this skill
 3. You have not linked the Node-RED alexa skill to eyour account, there is no access token in the database. 

You need to go to the skills list in the Alexa app and link the skill. This will ask for the username and password you used to set up the account on the site.

**Comment by neodevit** [comment]
alexa work fine
i have register skill con one password then changeit and configure nodered with another
THE PROBLEM now is that i have change password but not make change and i have reconfigured all using a old password
Now if the change password is finalizzed i must be rechange all but ok

Now a question
I use you skill for this but i want use it for a big project into my house
Your server not collapse or stop the service
I not want that service fall down
Tell me a service level rules
