### ISSUE TITLE
No Payload from alexa home node

### ISSUE THREAD

**Issue by nike12354** [hardillb/node-red-contrib-alexa-home-skill#56]
Hi,

I recently set up a new account with username nike12354 and added a new device "Testy" with On/Off option and smartplug property. After device search within alexa the device is found correctly.
After I deployed a node and linked it to my account, the device "Testy" showed up in the list.
My problem is, when I connect the node to a debug-node and set the alexa device "Testy" to on or off, no payload is shown in node red. The only debug info is "Error: connect ECONNREFUSED 34.240.81.189:8883" but the node shows "Connected" so this must be not relevant.

I played around with different topics on the node but it's everytime the same behaviour.

Do you have any hints for me?

EDIT:
Node-Red runs on iobroker on CentOS. Firewall is deactivated.

**Comment by hardillb** [comment]
The Error message is just the node trying to connect to a port, it will fall back to the second port after about 30 seconds.

You need to wait for the green dot and connected appears before you try and use the device.

- Do you get any error from Alexa when you try to turn the device on/off?
- Also have you asked Alexa to discover devices after each time you have changed the device on the website?
- Do you have a debug node connected to the output of the device node? if so first, is it enabled and second make sure it's set to whole message just to be sure you see everything

**Comment by nike12354** [comment]
Hey hardillb,

thanks for the quick response!

Yes, I already mentioned this in other closed issues here. I just wanted to state the full situation.

To your questions:
1) No, there are no errors if the auto-acknowledge checkbox is set to checked. Otherwise alexa tells me "Device not responding"
2) Yes all I did were clean tests, after deleting the device from alexa and a new deployment in Node-Red.
3) Yes the debug-node is connected to the output of the device node and all changes are deployed. I also played with the full debug msg, but same behaviour.

Do you need any other information?

Thanks a lot in advance for your time :)!

**Comment by hardillb** [comment]
If the device working when "auto-acknowledge"  ticked then the commands are making it to the node and the response is getting sent back to Alexa.

So this sounds like there is something wrong with Node-RED not passing the message on.

What version of NodeJS are you using to run Node-RED and what version of Node-RED?

**Comment by nike12354** [comment]
I will check this later on, when I am at home and reply again.

Thank you!

Outlook for Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by nike12354** [comment]
My Node.js runs at v8.15.0. 
Node-Red adapter in ioBroker is V1.7.1.

Anything wrong with it?
