### ISSUE TITLE
node label problem

### ISSUE THREAD

**Issue by njh** [hardillb/node-red-contrib-alexa-home-skill#6]
Hello,

Thank you for writing this node type - so pleased it is finally available in the Alexa app.

A minor bug is that the node label seems to arbitrarily change to the default 'Alexa Home' instead of the Device name.

<img width="177" alt="screenshot 2017-04-03 21 05 45" src="https://cloud.githubusercontent.com/assets/38734/24629825/5a13e936-18b2-11e7-970c-30b45cd2192b.png">

The version I have installed is:
```
  "name": "node-red-contrib-alexa-home-skill",
  "version": "0.1.15",
  "description": "This node allows you to hook up Node-RED to react to your Amazon Echo.",
```

Is there any more information I can give you to help diagnose the problem?

nick.

**Comment by hardillb** [comment]
That should be fixed in 0.1.15
What OS are you on, what browser?

But if you edit the node and change the device to something else and back again it should fix things.

**Comment by hardillb** [comment]
Also anything in the javascript console when you edit the node

**Comment by njh** [comment]
OS: MacOS 10.12.3
Browser: Chome 56.0.2924.87

> But if you edit the node and change the device to something else and back again it should fix things.

Yes, that has worked. thanks.


I am seeing lots of foo in the JavaScript console:
```
Node-RED: 0.15.3
VM563:27 foo 43
VM563:27 foo 606
VM563:27 foo 43
```
