### ISSUE TITLE
Make skill available for use in South Africa in English

### ISSUE THREAD

**Issue by antonybijsters** [hardillb/node-red-contrib-alexa-home-skill#60]
I have been trying to get the skill working in South Africa and have to assume that it is not zoned for here. Although there are 11 languages, the primary language in South Africa is English and it would be great if you can arrange to activate the skill here.

**Comment by hardillb** [comment]
Regional support is dictated by Amazon.

The list of supported languages is here:

https://developer.amazon.com/docs/custom-skill/develop-skills#in-multiple-languages.html

The skill should be active in all those languages, if that doesn't cover South Africa then you will need to raise this with Amazon

**Comment by antonybijsters** [comment]
Thank-you, I have logged it with Amazon.
