### ISSUE TITLE
Please allow error messages to be filtered from the debug window

### ISSUE THREAD

**Issue by bwims** [hardillb/node-red-contrib-alexa-home-skill#61]
Re: Issue #44, there are frequent spurious error messages of "ECONNREFUSED 34.240.81.189:8883"

The advice under Issue #44  is to ignore it, which would be fine, but the ability to filter in the debug window is greyed out.  (Hard to ignore when it is clogging up all the real debug messages.)

As it stands it happens so frequently that it makes use of the debug window difficult.  Ability to filter the messages out would help greatly.  Ability to suppress them would help even more.

Many thanks!

Brian Williams

**Comment by hardillb** [comment]
It should only happen once at start up. If it's happening multiple times then it sounds like you have one of the following:

 - Multiple Config nodes in a single instance of Node-RED. This is wrong, you should only enter your username/password once and share the config node between all the device nodes. You can check this by viewing all config nodes from the menu.

 - You have more than one Node-RED instance using the same username/password. This is unsupported, you can only have ONE instance.
