### ISSUE TITLE
#61 closed prematurely - more details here.

### ISSUE THREAD

**Issue by bwims** [hardillb/node-red-contrib-alexa-home-skill#62]
Hi,  I guess I worded #61 badly.  Agreed, this error does only occur once at each deploy, it seems, but when I am developing systems on multiple tabs,  I often make changes and redploy.  Each time I redeploy the message crops up and it would be really good if the filter node was not greyed out - the original request of #61 .  I confirm that I am using Alexa nodes as specified, but I like to get quite a bit of debug output.

Having said that, I am a newbie to node-red, so there may be a way of suppressing these messages, or diverting the debug output more conveniently that I have not spotted!

By the way, lastly but not least, I really appreciate being able to use Alexa from node-red!  The filtering would just be a very-nice-to-have!

Thanks!

**Comment by hardillb** [comment]
Change your deploy type to only deploy new/changed nodes (click the drop down on the right hand end of the deploy button). Then it won't restart the config node each time you deploy and you will only see the error once.

**Comment by bwims** [comment]
Many thanks!
