### ISSUE TITLE
alexa-home-conf:c05e67ac.2ebed8] Error: connect ECONNREFUSED 34.240.81.189:8883

### ISSUE THREAD

**Issue by jaeti01** [hardillb/node-red-contrib-alexa-home-skill#63]
Tried to use your service, but when I configure the node, it constantly disconnects.
node-red log shows:
alexa-home-conf:c05e67ac.2ebed8] Error: connect ECONNREFUSED 34.240.81.189:8883

**Comment by hardillb** [comment]
The usual reason for it connecting then disconnecting repeatedly is that you have multiple config nodes. You should only have one shared between each device.

The other option is that you have more than one Node-RED instance trying to use the same username/password. 

You can ignore the error

**Comment by jaeti01** [comment]
Thanks for the fast response!
Neither is the case, nor does it work. 
Though I have migrated my node-red from one machine to another. Not sure if that causes the old machine to still be registered?

**Comment by jaeti01** [comment]
Never mind, solved by creating a new account and recreating the devices.

**Comment by hardillb** [comment]
That is not the right approach.

You said you had moved the setup from one machine to another, did you stop the Node-RED instance on the old machine? If not did you make sure you removed the config node from flow the old version as well as the actual device nodes?

Also what is the old username?

I'm on holiday at the moment but I'll and find time to look at the logsf.

**Comment by jaeti01** [comment]
Yeah - the old instance has been shut down. 
i searched the new instance and it only shows a single config node.
Can I send you a PM with my old username and you just delete it?
Or is there a link on your page to get rid of the old one?

**Comment by hardillb** [comment]
Just post the username here

**Comment by jaeti01** [comment]
"till"

**Comment by hardillb** [comment]
I have looked at the logs and you definitely had 2 instance connected using the username "till" (and still have one connected along side the new "till-shuttle1" user.)

So there is either more than one config node or more than one Node-RED instance running

**Comment by jaeti01** [comment]
thanks for the feedback. Let me check that.

**Comment by jaeti01** [comment]
You have proven right. I indeed had a node-red instance with a left-over config node. 
thanks for your support!

**Comment by chadua** [comment]
17.09.2019, 00:28:08node: e6ce427b.3ff61
msg : error
"Error: connect ECONNREFUSED 34.240.81.189:8883"
username: chadua1

Help whenever possible. thank you

**Comment by hardillb** [comment]
@chadua This issue has been closed since June and you obviously haven't read it before posting.

If you are only seeing this in the debug sidebar once you should ignore it. If you are seeing it multiple times at regular intervals (not just when you deploy) then you need to make sure you only have just 1 config node that all the device nodes should point to it.

**Comment by chadua** [comment]
![1](https://user-images.githubusercontent.com/48262416/64995814-eead7900-d8e4-11e9-876e-ca4b24db7a62.JPG)

**Comment by hardillb** [comment]
@chadua I obviously wasn't clear earlier. Do not post to closed issues
