### ISSUE TITLE
Node red functionality lost when account password changed

### ISSUE THREAD

**Issue by MacFast** [hardillb/node-red-contrib-alexa-home-skill#64]
I needed to add a device but forgot my account password.  I reset it using the tool on the website.  Now my Alexa Home nodes don't work.  Neither the original one, nor the one I added (on the account website) after resetting the password.  They appear in Alexa but the node red nodes can't be configured.  I tried:
1. Unlinking and relinking the skill.  That works as far as having the devices appear in Alexa.
2. Deleting and recreating the nodes in node red - but there's no place to input my user name and the new password in the node configuration.  There's just a space for "name" and "type"
3. Uninstalling node-red-contrib-alexa-home-skill - but I can't.  The node listing in Palette says "Type already registered!"  and "in use"
4. Stopping and restarting node red - it didn't help with the above.
5. Rebooting the Raspberry Pi - no help

I'm running NodeRed v0.19.5 on a RaspBerry Pi 3B with Raspbian Jesse

**Comment by MacFast** [comment]
OK.  I fixed it.  Found this website: "https://discourse.nodered.org/t/how-to-uninstall-node/1278"
It explains how to uninstall nodes from the terminal instead of the Node Red Gui.  This means it can be done with Node Red stopped (command: node-red-stop).  I uninstalled, then reinstalled the "node-red-contrib-alexa-home-skill" and "node-red-contrib-alexa-home".  This allowed me to recreate the nodes with my new password.  At first the devices that I registered wouldn't appear in the pulldown.  Then I logged out and back in to the registration website and they appeared.  They now work with the Alexa skill.  I didn't have to unlink and relink it as I'd done that previously with the new password.

**Comment by hardillb** [comment]
You can change the password in the config node by clicking on the pencil icon at the end of the row with your username or by listing the config nodes in the sidebar.

The reason you couldn't uninstall was because you had not removed the config node
