### ISSUE TITLE
Documentation does not explain what "activity" means

### ISSUE THREAD

**Issue by bwims** [hardillb/node-red-contrib-alexa-home-skill#66]
Sorry I cannot find the answer to this:  The plugin allows for 
LIGHT:    
SWITCH:    
SMARTPLUG:    
THERMOSTAT:    
SMARTLOCK:    
ACTIVITY:   

But I don't know what "activity" means.  Could you please provide an example?

Many thanks!

**Comment by hardillb** [comment]
The application types are mainly just hints to Alexa  (and used to pick the icon in mobile app)

Activities are just for triggering things that might not be real devices, e.g. scenes -> dim lights and close blinds and turn on TV
