### ISSUE TITLE
alexa-node-red.bm.hardill.me.uk down ?

### ISSUE THREAD

**Issue by Oriondely** [hardillb/node-red-contrib-alexa-home-skill#68]
Hi,
my Alexa routines don't work anymore (they work till some hours ago). Whena I visit this page:
https://alexa-node-red.bm.hardill.me.uk/devices

I cannot login and see my devices list...

The returned error is:

**nginx error!
The page you are looking for is temporarily unavailable. Please try again later.

Website Administrator
Something has triggered an error on your website. This is the default error page for nginx that is distributed with the Amazon Linux AMI. It is located at /usr/share/nginx/html/50x.html

You should customize this error page for your own site or edit the error_page directive in the nginx configuration file /etc/nginx/nginx.conf.**

Thank you.

**Comment by hardillb** [comment]
Back up

**Comment by JackoAmmerlaan** [comment]
> Back up
working again.  Thnx for this great tool

**Comment by chrishem** [comment]
> Back up

Down again..

**Comment by hardillb** [comment]
Please do NOT use closed issues to report new failures
