### ISSUE TITLE
Manually acknowledging TurnOnRequest / TurnOffRequest

### ISSUE THREAD

**Issue by njh** [hardillb/node-red-contrib-alexa-home-skill#7]
Hi,

I am attempting to use the Alexa Home Skill in combination with my [node-red-contrib-owfs](https://github.com/njh/node-red-contrib-owfs) node.

I am trying to use the the 'Alexa Home Response' node to send the acknowledgment, once it has 'successfully' been switched on - but it does not seem to work:

<img width="1021" alt="screenshot 2017-04-03 20 59 05" src="https://cloud.githubusercontent.com/assets/38734/24631979/5c65c670-18ba-11e7-8139-61ca6a7f4148.png">

The Change Node converts msg.payload from true to 'on' and false to 'off'.

The lights successfully switch on and off but Alexa responses with:
> "Sorry the device 'Garden Lights' seems to be malfunctioning"

Should what I am attempting to do work?

nick.

**Comment by hardillb** [comment]
The payload is wrong, owfs is outputing a payload of `ok`, it needs to be `true` or `false`

From the docs:

> For TurnOnRequest/TurnOffRequest and SetPercentageRequest, IncrementPercentageRequest, DecrementPercentageRequest requests setting the msg.payload of the input message to true/false to signify success or failure.

**Comment by njh** [comment]
Oops, sorry I missed that. Working now.

I think I will change the OWFS node to use true/false as input and return values.

Thanks for the speedy response!
