### ISSUE TITLE
How to migrate systems when upgrading Node-Red with one system limitation?

### ISSUE THREAD

**Issue by bwims** [hardillb/node-red-contrib-alexa-home-skill#70]
Hi,

I am upgrading to Node Red 1.0 by installing it on another cpu and migrating systems across, a flow at a time.  With the limitations of one system access, I'm not sure how to migrate my Alexa Skills flows.  Would an appropriate method be to enable/disable flows which contain Alexa nodes in order to avoid the conflict, or is there a better way?  Alternatively, can I just ignore multiple ECONNREFUSED errors while testing?

Sorry if there is a more appropriate forum to post this question... please let me know for future ref. if there is.

Thanks! (Brilliant system, btw!)

**Comment by hardillb** [comment]
You can always ignore the ECONNREFUSED (until I get time to take the whole system for an hour or 2 to fix it)

As for migrating, the important bit is to disable the config node on the old system. By default config nodes are global so are not disabled with a given tab. You can change the scope of config nodes to bind them to a tab but I've never tried this so don't know if they will be disabled with the tab.
