### ISSUE TITLE
SetColorRequest with wrong values?

### ISSUE THREAD

**Issue by Marco4223** [hardillb/node-red-contrib-alexa-home-skill#71]
Hi,
I am using your great project to act with my HUE lights.
The only problem I have is to set the colors.
In the developer.amazon.com example I should request "Alexa, set the bedroom light to red." and the response should be somthing like this:
"payload": {
      "color": {
        "hue": 350.5,
        "saturation": 0.7138,
        "brightness": 0.6524
      }

What I get in Redmatic is:
hue: 348
saturation: 0.251
brightness: 1

But why? Is this a bug?
Many thx for your help.

**Comment by hardillb** [comment]
I'm not sure what you are asking here. It's not clear which of those you are getting as output from my node.

Also I  have no idea what redmatic is?

**Comment by Marco4223** [comment]
Wow, that was a fast answere.
Ok, Redmatic is a Homatic System where you can put on Node-Red.
And yes, it was nt clear. 
The ourput 
hue: 348
saturation: 0.251
brightness: 1
is from node-red-contrib-alexa-home-skill when I'm asking Alexa for light red (Rosa in german)
from amanoz dev I understood that I should get back this:
"hue": 350.5,
"saturation": 0.7138,
"brightness": 0.6524

**Comment by hardillb** [comment]
I don't change the values passed to the service by Amazon at all, they get passed straight through as the msg.payload.
