### ISSUE TITLE
ALEXA con node red

### ISSUE THREAD

**Issue by giohassio** [hardillb/node-red-contrib-alexa-home-skill#72]
Ciao e complimenti per tutto quello che fai. Ho seguito la tua guida ma non riesco a gestire i miei dispositivi su HASSIO.
Vedo che funziona molto bene l'integrazione tra alexa e node red, ma pur avendo usato le stesse entita' non vedo cambiare lo stato su Hassio.
Come posso risolvere ?
ti ringrazio

**Comment by hardillb** [comment]
I'm sorry, you'll have to post in English if you want me to be able to help.

**Comment by giohassio** [comment]
Hello and congratulations for everything you do. I followed your guide but I can't manage my devices on HASSIO.
I see that the integration between alexa and node red works very well, but despite having used the same entities, I don't see the state changing to Hassio.
How can I solve it?
thank you

**Comment by hardillb** [comment]
OK, still don't understand what you are asking.

This service is purely for linking Alexa with Node-RED, it has no support for Hassio.

**Comment by giohassio** [comment]
I thought that if we could use the mqtt protocol we could use ... thanks
