### ISSUE TITLE
Connect error

### ISSUE THREAD

**Issue by anwar3000** [hardillb/node-red-contrib-alexa-home-skill#74]
good day..!

below error i am getting
"Error: connect ECONNREFUSED 34.240.81.189:8883"

1> no other nodes having the same username 
2> I tried with a new username to verify but still the same issue 
user name - anwar3000 and anwar3001

**Comment by hardillb** [comment]
That is perfectly normal, you can ignore the error,  just leave it 30 seconds and it will connect to the other broker instance.
