### ISSUE TITLE
Getting HTTP 404 for download device list

### ISSUE THREAD

**Issue by atomroflman** [hardillb/node-red-contrib-alexa-home-skill#75]
When I am opening the Node Red flow configuration of an instance of 'Alexa Home' I can sign into my account wich is marked as connected.
Anyways the device list keeps empty.
I can see the devices in the alexa app.

I tried: 
-rediscovering devices
-restarting node red 
-reconnecting alexa account twice 
-recreating my account 
-recreating the flow

Url: http://{MyserverIP}:1880/alexa-home/devices/{MyUserID}
accounts: atomroflman & greg-e

**Comment by hardillb** [comment]
That implies that the Node has not been able to retrieve the live of devices from the backend.

Have you restarted Node-RED?

Also what version of Node-RED, NodeJS and the node are you running?

Also are you trying to use both usernames (atomroflman & greg-e) in the same Node-RED instance?

**Comment by hardillb** [comment]
The logs are showing 401 errors on the backend which implies a problem with your password. Does it by any chance include a `@` symbol?

**Comment by hardillb** [comment]
Also are you seeing anything in the Node-RED log that looks like:

    Problem looking up [username]'s devices

**Comment by hardillb** [comment]
If not a `@` how about a `+` in the password?

If you have either, logout of the website and use the lost password option to try a different password without either `@` or `+`.

**Comment by atomroflman** [comment]
Hi Hardillb,

thank you for your response.
I'm using node version 10.13 and node-red 1.0.2. The node red instance is integrated into an iobroker.

Other urls work fine, like "alexa-home/refresh/{MyUserID}" 
but /alexa-home/devices/{MyUserID} returns 404

Thank you

**Comment by hardillb** [comment]
refresh will, it doesn't actually wait for the get device call to finish.

As I said, this is most likely a problem with the password you are using

**Comment by atomroflman** [comment]
Ok you are right, I resettet the password to a simpler one and now it is working.
Thank you 👍

**Comment by hardillb** [comment]
Just to be clear I believe this to be a bug in the require library.
