### ISSUE TITLE
German "dunkler" not working anymore

### ISSUE THREAD

**Issue by netmb** [hardillb/node-red-contrib-alexa-home-skill#76]
Hi,

since a few weeks the german command "Licht dunkler" (light darker) is no longer working. It worked for more than a year without problems. You now have to say "Licht dimmen" (light dim) to get the desired result.

If you say "Licht dunkler" now, you always get "25" - IncrementPercentageRequest.
Before you got "-25" - DecrementPercentageRequest.

Any ideas? Is this an Alexa oder skill-related?

**Comment by hardillb** [comment]
Sorry, all the voice recognition is handled by Amazon before it ever makes it to the skill.

This must have been a change made by them.

**Comment by netmb** [comment]
Ok, thanks for your quick response.
