### ISSUE TITLE
Temperature still only available for UK and US?

### ISSUE THREAD

**Issue by DomTo** [hardillb/node-red-contrib-alexa-home-skill#77]
Are the following functions to get temperature information still only available for UK and US?
- GetTemperatureReadingRequest 2,3
- GetTargetTemperatureRequest 2,3

It's not working for Alexa in Germany.

**Comment by hardillb** [comment]
That's all controlled from Amazon's side, so if it's not working then probably (it may be an artifact of using the v2 API)

**Comment by DomTo** [comment]
Okay, thank you very much for the fast response. 👍
