### ISSUE TITLE
can't run node-red-contrib-alexa-smart-home

### ISSUE THREAD

**Issue by dror23** [hardillb/node-red-contrib-alexa-home-skill#78]
Hey evreyone, i'm getting the following error on node -red when i'm trying to run a flow:
Error: connect ECONNREFUSED 34.240.81.189:8883
does any one know how to fix that?

**Comment by hardillb** [comment]
Ignore it

The node will reconnect on the other port in 30 seconds

**Comment by dror23** [comment]
Thank you very much for your quick answer!
