### ISSUE TITLE
Portuguese language request

### ISSUE THREAD

**Issue by aarantes23** [hardillb/node-red-contrib-alexa-home-skill#79]
Hi.
At first place, I would like to thank you this project.
Sadly the skill is not available on the Brazilian store. Perhaps this is because Amazon Echo has been available in Brazil for a short time.
Is it possible to make it accessible from the Brazilian store?
And how can I contribute to get Brazilian Portuguese language for the Alexa skill?
Many thanks again!
Regards.

**Comment by hardillb** [comment]
Hi,

The translations have all been done, unfortunately when I tried to submit them, the reviewers raised a bunch of problems with all the other languages that have already been approved. At the moment I don't have time to work out what is now "wrong" with the other languages.

If I get some time I will try and submit the Brazilian translations again and see what happens.

**Comment by aarantes23** [comment]
Great!
Thank you so much!

**Comment by thiagoprati** [comment]
Sorry to bother you on this issue again. has there been any upgrade on PT support? I'd love to help anyway I can.

**Comment by hardillb** [comment]
No, and it is unlikely to happen

**Comment by paulomar** [comment]
I'm a developer and willing to contribute. I'm in Brazil and interested in node-red skill, so if you want a hand I can try to help

**Comment by hardillb** [comment]
Just to be clear, it is not development effort here, it is that Amazon appears to have changed their approval requirements and want to apply them retroactively to all the already approved languages text and descriptions.

Having to redo all the translations to meet these new requirements is not going to happen. This skill is basically in maintenance mode.

**Comment by thiagoprati** [comment]
If we can  Help in anyway, just say it. Is it possible to organize the translations in a table?

**Comment by thiagoprati** [comment]
Would you consider openning up your work so we can reproduce it in our language?

**Comment by hardillb** [comment]
All the code is already on GitHub, but you can't deploy it any more because it uses the v2 Alexa Smart Home API and Amazon will not let you deploy a skill that doesn't use v3. To move it v3 would require a total rewrite of the skill.

**Comment by hardillb** [comment]
I have resubmitted the Portuguese translation to see what happens, we'll see what the Amazon team come back with.
