### ISSUE TITLE
SetTemperatureRequest -> SetTargetTemperatureRequest

### ISSUE THREAD

**Issue by njh** [hardillb/node-red-contrib-alexa-home-skill#8]
I was just having trouble getting the ```SetTemperatureRequest``` command to work and found that it was coming through as ```SetTargetTemperatureRequest```.

https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/smart-home-skill-api-reference#settargettemperaturerequest

Did they change it?

**Comment by hardillb** [comment]
No, typo in my docs
