### ISSUE TITLE
The site seems to be down

### ISSUE THREAD

**Issue by mrohner** [hardillb/node-red-contrib-alexa-home-skill#80]
alexa-node-red.bm.hardill.me.uk

**Comment by hardillb** [comment]
Nope, it's up. The ISP that hosts the DNS for the donation is having issues at the moment, but the site is up.

Exactly what error are you seeing?

**Comment by mrohner** [comment]
Problem seems solved. This was the message:

This site can’t be reached alexa-node-red.bm.hardill.me.uk’s server IP address could not be found.

Thanks for providing this service.
