### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by zraken** [hardillb/node-red-contrib-alexa-home-skill#84]
Followed steps from documentation but I'm seeing this in the node-red log:
```
Jul 06 17:38:30 rpi2 Node-RED[5350]: 6 Jul 17:38:30 - [error] [alexa-home-conf:eac45643.46e308] Error: connect ECONNREFUSED 34.240.81.189:8883
Jul 06 17:38:36 rpi2 Node-RED[5350]: 6 Jul 17:38:36 - [error] [alexa-home-conf:eac45643.46e308] Error: Connection refused: Not authorized
```
This has been going on for a long time so I deleted the node. On the Alexa side I was able to link the account and discover devices correctly. The only thing I did different is that I deployed tab with "Alexa Home" after setting up account credentials and prior to trying to look up devices. As soon as I hit deploy I see these errors.

**Comment by hardillb** [comment]
Ignore that error, 30 seconds later it will connect on port 1883 it is it just using a fail over address that it currently not running.

To prevent seeing the message on every deploy change your deploy type to just changed nodes (click the arrow on the end of the deploy button), since the config node will not change it won't tear the connection down and restart it on each deploy

**Comment by zraken** [comment]
This error has been going on for minutes, these messages are repeating every 5-6 seconds. Also, I am not seeing the devices in the dropdown (I hit refresh still nothing).

**Comment by hardillb** [comment]
Then your password is wrong (or it contains a `@` symbol) change the password by using the forgotten password link here https://alexa-node-red.bm.hardill.me.uk/lostPassword

**Comment by hardillb** [comment]
Actually if it's failing to connect to the MQTT broker then the password is just wrong, it's not the `@` symbol

**Comment by zraken** [comment]
My password contains one uppercase letter and some lowercase letters and a couple of numbers. Is there a limit on the number of characters?

**Comment by hardillb** [comment]
You must have a type when you entered it into Node-RED is the MQTT connection is failing.

**Comment by zraken** [comment]
Is there a way to delete my account and restart from scratch?

**Comment by hardillb** [comment]
Use the link I posted to change your password

**Comment by zraken** [comment]
Ok, I'll try that.
