### ISSUE TITLE
Error: connect ECONNREFUSED 34.240.81.189:8883

### ISSUE THREAD

**Issue by Senbei123** [hardillb/node-red-contrib-alexa-home-skill#85]
Hi,

I get this issue every time, when I deploy a change in nodered.

Only one config node available. Username 'Senbei'.

Can you support?

Br,
Senbei

**Comment by hardillb** [comment]
Ignore it, it will reconnect on the other port about 30 seconds later.

You can also set Node-RED to only deploy changed nodes (since the config node will never change after the first deploy) and it won't tear down and restart the connection on every deploy
