### ISSUE TITLE
Error: connect ECONNREFUSED 34.240.81.189:8883 

### ISSUE THREAD

**Issue by tecnicocasella** [hardillb/node-red-contrib-alexa-home-skill#87]
Hi, i'm trying to connect my node-red application to my echo dot but i notice this error configurating the node.
I saw this issue posted on other closed discussion but the solution provided doesn't work for me. 
I have configured only one node and one node-red application for my account but i still have the node flagged as "disconnect". I have linked the account on my alexa device and the discover goes well, so i find the device configured on my account. 
I've done some test:
- restart the node red application
- created and configured another account
- deleted and searched the device again
- unlinked and relinked the alexa skill
...but none of them works.
My account name is "casella".

Thanks for help and excuse me for bad english.

**Comment by hardillb** [comment]
Assuming you have only created one configuration node (where you entered the username/password) that is shared between all the device nodes then this message can be ignored. If you **wait 30 seconds** the system will connect to the alternate backend endpoint. This is part of a fallback system should the backend be down for some reason.

You can limit the  number of times the message is shown by setting the Node-RED deploy button to only deploy changed nodes.

If after a single deployment you see this message repeated,  with the device nodes alternating from connected to disconnected then you most likely have  multiple configuration nodes. This is wrong, you should only have one for this service. You can get Node-RED to show you all the configuration nodes from  the menu in the top right corner. From here you should delete all but one  of the `alexa-home-conf` nodes and then update all the device nodes to point to this remaining configuration node.

**Comment by tecnicocasella** [comment]
Dear mr. Hardill, thanks for reply.

I would like to send u the screen of my node-red flow. As u can see, in the menu i have only one alexa-home-conf node.
I assume is correctly configurated with my account because the device nodes was automatically detected as i have configurated on web site. I could also assume to have correctly configurated the link between alexa skill and my account, because the device was finded by echo dot.

*) Could be an issue of my firewall? – i mean, there is some particular port that i have to open?
*) Could be an issue of my echo dot version that coud be not supported? I have software version nr. 3926570372

Thanks.
Best regards
Da: Ben Hardill <notifications@github.com>
Inviato: martedì 28 luglio 2020 14:11
A: hardillb/node-red-contrib-alexa-home-skill <node-red-contrib-alexa-home-skill@noreply.github.com>
Cc: Massimo D'Agostino <massimo@casellasrl.com>; Author <author@noreply.github.com>
Oggetto: Re: [hardillb/node-red-contrib-alexa-home-skill] Error: connect ECONNREFUSED 34.240.81.189:8883 (#87)


Assuming you have only created one configuration node (where you entered the username/password) that is shared between all the device nodes then this message can be ignored. If you wait 30 seconds the system will connect to the alternate backend endpoint. This is part of a fallback system should the backend be down for some reason.

You can limit the number of times the message is shown by setting the Node-RED deploy button to only deploy changed nodes.

If after a single deployment you see this message repeated, with the device nodes alternating from connected to disconnected then you most likely have multiple configuration nodes. This is wrong, you should only have one for this service. You can get Node-RED to show you all the configuration nodes from the menu in the top right corner. From here you should delete all but one of the alexa-home-conf nodes and then update all the device nodes to point to this remaining configuration node.

**Comment by hardillb** [comment]
How long have you left the system after hitting deploy? It will ALWAYS show the error you have mentioned, but if you just sit there and leave it, it will connect to the same IP address but with port 1883.

If you getting 2 different errors, one with port 8883 and one with 1883 then you need to allow outbound connections on port 1883. But you still haven't answered what happens if you just wait.

**Comment by tecnicocasella** [comment]
Dear mr. Hardill, thanks for reply and for time that you are spending on my issue.

I would like to send u the screen of my log. As u can see, i left the system up for about 10 minutes but i still have the node alternating disconnect and reconnecting status. The error message always refer to port 8883 and i have no evidence that it switch to port 1883.

Thanks.
Best regards

Da: Ben Hardill <notifications@github.com>
Inviato: martedì 28 luglio 2020 17:45
A: hardillb/node-red-contrib-alexa-home-skill <node-red-contrib-alexa-home-skill@noreply.github.com>
Cc: Massimo D'Agostino <massimo@casellasrl.com>; Author <author@noreply.github.com>
Oggetto: Re: [hardillb/node-red-contrib-alexa-home-skill] Error: connect ECONNREFUSED 34.240.81.189:8883 (#87)


How long have you left the system after hitting deploy? It will ALWAYS show the error you have mentioned, but if you just sit there and leave it, it will connect to the same IP address but with port 1883.

If you getting 2 different errors, one with port 8883 and one with 1883 then you need to allow outbound connections on port 1883. But you still haven't answered what happens if you just wait.

**Comment by hardillb** [comment]
Images are not included when you reply to issues via email.

Also if it is just alternating between connected and disconnected then you 100% have more than one config node using the same username/password. This could either be as multiple config nodes in a single instance of Node-RED  or multiple Node-RED instances.
