### ISSUE TITLE
Site down NGINX error

### ISSUE THREAD

**Issue by Fuzz-Software** [hardillb/node-red-contrib-alexa-home-skill#88]
Site not working for about an hour or so @ 01:28 UTC.

**Comment by JackoAmmerlaan** [comment]
Same problem here.

**Comment by hardillb** [comment]
up

**Comment by JackoAmmerlaan** [comment]
> up

Thnx. The kids are happy again. ;-)

**Comment by Fuzz-Software** [comment]
Thanks, this is the first time I've noticed an outage in about three years of using the service.
