### ISSUE TITLE
Authentication failed: "no body" after first routine call

### ISSUE THREAD

**Issue by M0ebiu5** [hardillb/node-red-contrib-alexa-home-skill#89]
I'm getting continuously the error 'Authentication failed: "no body"' a few seconds after fresh authentication and invoking a speak routine command. (v 3.10.4)
![Screenshot at 2020-10-28 12-34-31](https://user-images.githubusercontent.com/9152698/97431264-50c71300-191a-11eb-8684-0db8bc3695b1.png)

How can i fix it?

**Comment by hardillb** [comment]
That node is nothing to do with this service

**Comment by M0ebiu5** [comment]
I'm sorry!
