### ISSUE TITLE
Can't find devices, 404 at https://alexa-node-red.bm.hardill.me.uk/

### ISSUE THREAD

**Issue by JoshPenn** [hardillb/node-red-contrib-alexa-home-skill#9]
My Alexa can no longer find devices. 
I also found that https://alexa-node-red.bm.hardill.me.uk/ returns a 404 error, which I assume is related.

Response: `404 Not Found: Requested route ('alexa-node-red.bm.hardill.me.uk') does not exist.
`

**Comment by hardillb** [comment]
yeah, it's hosted on IBM Bluemix which is down for maintenance at the moment. Hopefully it will be back soon.

I'm planning a move to AWS when I get some spare time now that Amazon are offering $100 a month in costs to host Alexa Skills

**Comment by JoshPenn** [comment]
Thanks for the update!

I found this which may be helpful for other users who may be tracking: https://console.ng.bluemix.net/status/?cm_mc_uid=04508445980514921083627&cm_mc_sid_50200000=1492108362&cm_mc_sid_52640000=1492108362 (EU-GB region)

**Comment by JoshPenn** [comment]
Bluemix appears to be back up and I can now find devices. Thanks again!

**Comment by hardillb** [comment]
Looks like its back up
