### ISSUE TITLE
Passing custom values via alexa skill possible?

### ISSUE THREAD

**Issue by MadScienzzz** [hardillb/node-red-contrib-alexa-home-skill#92]
Hi.

Just started using the service yesterday - fantastic stuff!

Just wondered - is there a way to pass custom values?  I am linking to an ESP8266 (wemos d1 mini) which is attached to ws2811 lights and I've programmed different sequences.  At the moment, I have just created separate devices for each sequence, all pointed to the esp8266, but it's long winded and as there is only one device (with different values passed to trigger the sequences, rather than just true or false) it would make life easier (just using a switch in node red with multiple outputs/values to the same function/device?

Cheers,

Glenn (fellow UK dev!)

**Comment by hardillb** [comment]
No, there is no way to add anything to the messages that are delivered from Amazon.
