### ISSUE TITLE
SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by Holger-Will** [hardillb/node-red-contrib-alexa-home-skill#93]
trying to install gives an Error 

> 13 Dec 06:26:07 - [warn] [node-red-contrib-alexa-home-skill/alexa] SyntaxError: Invalid or unexpected token

I'm on Windows 10 and tried with different versions of node > 12.0.0
tried installing via the pallette, by hand unsing npm and cloning the repository and running it locally.

the problem is caused by the mqtt package. it seems version 2.x.x will cause this Error. after trying mqtt v2.0.1 and v2.18.8 with node version 15,14,13 and 12 (all producing the same error) i gave up digging any further.

updating to mqtt@latest (4.2.6) fixes the issue...

**Comment by hardillb** [comment]
I should technically support Node 8 until Node-RED v2.0 ships early next year.

It looks like core Node-RED has pinned at v4.2.6 for the same reason
