### ISSUE TITLE
[error] [alexa-home-conf: bd132216.381cf] Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by maverik80** [hardillb/node-red-contrib-alexa-home-skill#95]
hello, new installation on hassos 5.8 and node red when installing the alexa skill node I report this error, how can I solve it? I was reading about a double instance but I honestly don't know how. [error] [alexa-home-conf: bd132216.381cf] Error: connect ECONNREFUSED

**Comment by hardillb** [comment]
You just ignore the ECONNREFUSED error for port 8883. This is just the system trying to connect to a fall back broker. It will reconnect to port 1883 in 5 seconds.

If you want to stop the nodes reconnecting every time you deploy, change the deployment type to just changed nodes (click the down arrow on the deploy button)

You only need to worry about multiple config nodes if the nodes repeatedly flip between connected/disconnected when you haven't deployed any changes

**Comment by maverik80** [comment]
but then I don't know if it is related because I had node red working perfectly on raspbian ha, then my sd was ruined and I opted for an ssd with hassod 5.8 and since then alexa no longer takes voice commands to control my lg tv than before it worked well, I can't figure out what I'm doing wrong, the nodes are connected but they don't execute the command

**Comment by hardillb** [comment]
If the nodes show connected then attach a debug node to the Alexa node to see if any messages are arriving when you talk to the echo device.

I can't debug this while I'm at work, but you are going to have to supply a LOT more information

**Comment by maverik80** [comment]
unfortunately even with a debug node, attached to the alexa home node I do not receive debugging, alexa at the volcale command replies ok but it is as if she does not know what to do, the skill on the alexa app is connected correctly and finds the dummy entity but does not start no command

**Comment by hardillb** [comment]
I'll try and look at the logs tonight. What is your username and what is the device name

**Comment by hardillb** [comment]
It looks like you have 2 usernames (maverick80 & mav.erik) are you sure you have linked the right one with Alexa and you have signed into the node in node-red with the right one?

The mav.erik user only has one device "apri netflix"

The maverick80 user a has 4 devices.

You can only link one of these accounts at once with Alexa

**Comment by hardillb** [comment]
I'm going to close this as I've not heard anything in the last 20 days
