### ISSUE TITLE
Custom commands request. 

### ISSUE THREAD

**Issue by Thenas** [hardillb/node-red-contrib-alexa-home-skill#97]
is it possible to add custom commands?, i want to add a "mode" command for change the mode of my LEDs strip.

**Comment by hardillb** [comment]
No, it is not possible with the version of the Alexa Smart Home API the skill is based on

**Comment by hardillb** [comment]
But you can just create devices with the mode names and on/off traits.

E.g. "Alexa, Turn on rainbow" instead of "Alexa, Set LEDs to rainbow"
