### ISSUE TITLE
Output of Alexa device that initiates the flow

### ISSUE THREAD

**Issue by GetUpdate** [hardillb/node-red-contrib-alexa-home-skill#98]
Backround: I run 5 Alexa devices within our smart home.  I'd like to start a function and the reply I'd like to send to only the device the flow was initiated.  
-> Can I get the initiating device back from the node-red-contrib-alexa-home-skill ?

THX and have a nice xmas. 

Michael 

PS: Du to GetTemperatureReadingRequest is not available in good old Germany, I' would be able to do it anyhow If I could get the initiating device...

**Comment by hardillb** [comment]
No, the device ID is not provided in the information passed from Amazon to the skill
