### ISSUE TITLE
Question: Just a status message

### ISSUE THREAD

**Issue by hklages** [hardillb/node-red-contrib-alexa-home-skill#99]
Hi. Is it possible to just get a spoken message. I couldn't find anything. 

For instance: Alexa command "switch status on" triggers a flow to retrieve my home status (open windows, open blinds, heating profile, ...) as  simple text message which is then spoken out by an echo device (the same one action on the "switch status on " command.

**Comment by hardillb** [comment]
No, there is no way to send an custom response messages
